#!/bin/sh -e

##########################################################################
#   Script description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2014-11-25  root        Begin
##########################################################################

usage()
{
    printf "Usage: $0 pkgsrc-prefix\n"
    exit 1
}


##########################################################################
#   Function description:
#       Pause until user presses return
##########################################################################

pause()
{
    local junk
    
    printf "Press return to continue..."
    read junk
}


##########################################################################
#   Main
##########################################################################

if [ $# != 1 ]; then
    usage
fi

prefix=$1

rm -f /etc/init.d/slurm
sed -e "/^BINDIR=/ i exec_prefix=$prefix/pkg-1\nprefix=$prefix/pkg-1\n" \
    $prefix/pkg-1/share/examples/slurm/init.d.slurm > /etc/init.d/slurm
chmod 755 /etc/init.d/slurm

mkdir -p /var/log/slurm
chown slurm:slurm /var/log/slurm

chkconfig slurm on

cat << EOM

Run "service slurm start" after installing

$prefix/pkg-1/etc/slurm.conf.

EOM
pause

