#!/bin/sh

if [ `hostname -s` != 'login' ]; then
    printf "$0 can only be run on the primary login node.\n"
    exit 1
fi

for node in `cluster-backup-login-nodes`; do
    echo $node

    # Syncing .ssh could kill ssh keys.
    rsync -av --exclude slurm --exclude .ssh /root ${node}:/
    rsync -av --exclude slurm /home ${node}:/
    ssh ${node} 'restorecon -R -v /home/*/.ssh'
    rsync -av /etc/security/limits.d ${node}:/etc/security
    rsync -av /usr/local ${node}:/usr
    rsync -av /usr/pkg* ${node}:/usr
    
    # This causes updates to be installed.  Use cached RPMs instead?
    # pkgs=`yum list installed | awk ' { print $1 }'`
    # ssh ${node} yum install $pkgs
done

slurm-sync-backup-login

