#!/bin/sh -e

##########################################################################
#   Script description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2013-12-26  root        Begin
##########################################################################

usage()
{
    printf "Usage: $0 node-type\n"
    exit 1
}


##########################################################################
#   Function description:
#       Pause until user presses return
##########################################################################

pause()
{
    local junk
    
    printf "Press return to continue..."
    read junk
}


##########################################################################
#   Main
##########################################################################

if [ $# != 1 ]; then
    usage
fi

node_type=$1

# Caution: 
# The line below is modified by install.sh. Be careful not to replace
# %%PREFIX%% with a hard-coded prefix from an installed script.
prefix=%%PREFIX%%

munge_etc="$prefix/etc/munge"
mkdir -p -m 0700 $munge_etc

case $node_type in
'head')
    if [ ! -e $munge_etc/munge.key ]; then
	printf "Generating munge key...\n"
	dd if=/dev/urandom bs=1 count=1024 > $munge_etc/munge.key
    fi
    ;;

'compute')
    if [ ! -e $munge_etc/munge.key ]; then
	printf "Host name or IP address of head node? "
	read head_node
	scp ${head_node}:$munge_etc/munge.key $munge_etc
    fi
    ;;

*)
    printf "$0 is only for head and compute nodes.\n"
    exit 1
    ;;
esac

chmod 400 $munge_etc/munge.key

mkdir -p /var/log/munge /var/run/munge /var/lib/munge
chown -Rh munge:munge \
    $prefix/var/log/munge \
    $prefix/var/run/munge \
    $prefix/var/lib/munge \
    $munge_etc
chmod 755 $prefix/var/run/munge

# RHEL init script
rm -f /etc/init.d/munge
init_script=$prefix/share/examples/rc.d/init.d/munge
if [ -e $init_script ]; then
    ln -s $init_script /etc/init.d/munge
fi
chkconfig munge on
service munge restart

