#!/bin/sh

##########################################################################
#   Function description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2016-08-15  root        Begin
##########################################################################

if ! iptables-save | fgrep -q -- "-j CLUSTER"; then
    iptables -N CLUSTER
    iptables -I INPUT $INSERTLN -j CLUSTER
    iptables -I CLUSTER -p udp -s 192.168.0.0/22 -j ACCEPT
    iptables -I CLUSTER -p tcp -s 192.168.0.0/22 -j ACCEPT
    service iptables save
fi
