#!/bin/sh -e

##########################################################################
#   Script description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2015-06-17  root        Begin
##########################################################################

usage()
{
    printf "Usage: $0 domain\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 1 ]; then
    usage
fi

# Without a domain, users are mapped as nobody
domain=$1

sed -i "s|.*Domain = .*|Domain = $domain|" /etc/idmapd.conf
cluster-run "sed -i 's|.*Domain = .*|Domain = $domain|' /etc/idmapd.conf" all

service rpcidmapd restart
cluster-run "service rpcidmapd restart" all

