#!/bin/sh -e

for user in `cluster-users`; do
    echo $user
    chage -M 365 -W 14 $user
    for node in `cluster-backup-login-nodes` `cluster-io-nodes`; do
	echo $node
	ssh $node chage -M 365 -W 14 $user
    done
done

