#!/bin/sh -e

##########################################################################
#   Script description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2013-12-26  root        Begin
##########################################################################

usage()
{
    printf "Usage: $0 node-type\n"
    exit 1
}


##########################################################################
#   Function description:
#       Pause until user presses return
##########################################################################

pause()
{
    local junk
    
    printf "Press return to continue..."
    read junk
}


##########################################################################
#   Main
##########################################################################

if [ $# != 1 ]; then
    usage
fi

NODE_TYPE=$1

if fgrep 'release 6' /etc/redhat-release; then
    RHEL_VERSION=6
else
    RHEL_VERSION=7
fi

prefix=/usr/pkg
munge_etc="$prefix/etc/munge"
mkdir -p -m 0700 $munge_etc

case $NODE_TYPE in
'head')
    if [ ! -e $munge_etc/munge.key ]; then
	printf "Generating munge key...\n"
	dd if=/dev/urandom bs=1 count=1024 > $munge_etc/munge.key
    fi
    ;;

'compute')
    if [ ! -e $munge_etc/munge.key ]; then
	printf "Error, missing munge key.  Should have been pushed over by cluster-sync-node.\n"
	exit
    fi
    ;;

*)
    printf "$0 is only for head and compute nodes.\n"
    exit 1
    ;;
esac

# https://github.com/dun/munge/wiki/Installation-Guide
# FIXME: Move this to munge pkg?
mkdir -p -m 711 $prefix/var/lib/munge
mkdir -p -m 700 $prefix/var/log/munge
mkdir -p -m 755 $prefix/var/run/munge
mkdir -p -m 400 $munge_etc

chown -Rh daemon:daemon \
    $prefix/var/log/munge \
    $prefix/var/run/munge \
    $prefix/var/lib/munge \
    $munge_etc

# RHEL init script
case $RHEL_VERSION in
6)
    rm -f /etc/init.d/munge
    init_script=$prefix/share/examples/rc.d/init.d/munge
    if [ -e $init_script ]; then
	ln -s $init_script /etc/init.d/munge
    fi
    chkconfig munge on
    service munge restart
    ;;

7)
    init_script=$prefix/lib/systemd/system/munge.service
    # FIXME: Move this to munge pkg?
    sed -i'' 's|=munge|=daemon|g' $init_script
    systemctl disable munge.service || true
    systemctl enable $init_script || true
    systemctl daemon-reload
    systemctl restart munge.service
    ;;

*)
    printf "Unsupported RHEL version: $RHEL_VERSION\n"
    exit 1
esac
