#!/bin/sh -e

db=/usr/local/cluster/compute-node-yum-packages

if [ ! -e $db ]; then
    cat << EOM

Missing $db.

$db should contain a list of packages to be installed on every compute node,
all on a single line.

EOM
cat $db

