#!/bin/sh -e

cd /usr/pkgsrc-1
if [ -e jb-wip ]; then
    cd jb-wip
    svn up
else
    svn co svn+ssh://bacon@jbacon.acadix.biz/home/bacon/SVN/jb-wip
fi

# Install from pkgsrc
cd /usr/pkgsrc-1/jb-wip/denyhosts
bmake install

# Enable init script
chkconfig denyhosts on
service denyhosts restart

