#!/bin/sh -e

# Without this, users are mapped as nobody

# Head
sed -i 's|#Domain = .*|Domain = cluster|' /etc/idmapd.conf
service rpcidmapd restart

# Add this to cluster-setup
cluster-run \
    "sed -i 's|#Domain = .*|Domain = cluster|' /etc/idmapd.conf; service rpcidmapd restart" \
    all

