#!/bin/sh -e

yum install httpd php

# php-mysql php-devel php-gd php-pecl-memcache php-pspell php-snmp \
#    php-xmlrpc php-xml

ganglia=/var/lib/ganglia
mkdir -p $ganglia/rrds
chown nobody:nobody $ganglia/rrds/
restorecon -R -v $ganglia

#ganglia_web=/usr/pkg-1/var/lib/ganglia-web
ganglia_web=/var/lib/ganglia-web
set -x
cp -Rp /usr/pkg-1/$ganglia_web /var/lib
#mkdir -p $ganglia_web/dwoo/compiled
#mkdir -p $ganglia_web/dwoo/cache
chown -R apache:apache $ganglia_web
chmod -R u+rwX,g-w $ganglia_web

# selinux attempted fixes
#chcon -R -t httpd_sys_rw_content_t $ganglia_web
#setsebool -P allow_httpd_sys_script_anon_write 1
#restorecon -R -v $ganglia_web
#setsebool -P allow_httpd_anon_write=1
# FIXME: Temporary hack
echo 0 > /selinux/enforce

DATADIR=/usr/pkg-1/share/cluster-admin
cp $DATADIR/WWW/global_styles.css $DATADIR/WWW/centos-power.jpg /var/www/html
chmod a+r /var/www/html/*

if [ ! -e /var/www/html/index.php ]; then
    printf "Cluster name as it should appear on the web? "
    read name
    sed -e "s|%%HOSTNAME%%|$name|g" $DATADIR/WWW/index.php > /var/www/html/index.php
fi

ln -sf /usr/pkg-1/share/examples/rc.d/gmond.init /etc/init.d/gmond
chkconfig --add gmond
service gmond restart

ln -sf /usr/pkg-1/share/examples/rc.d/gmetad.init /etc/init.d/gmetad
chkconfig --add gmetad
service gmetad restart

httpd_conf='/etc/httpd/conf/httpd.conf'

if ! fgrep -q '/ganglia/' $httpd_conf; then

    cat << EOM >> $httpd_conf

Alias /ganglia/ "/usr/pkg-1/share/httpd/htdocs/ganglia/"

<Directory "/usr/pkg-1/share/httpd/htdocs/ganglia/">
    Options Indexes FollowSymlinks MultiViews
    AllowOverride None
    Order allow,deny
    Allow from all
    <IfModule dir_module>
	DirectoryIndex index.php
    </IfModule>
</Directory>
EOM
fi

service httpd restart

