#!/bin/sh -e

##########################################################################
#   Function description:
#       Pause until user presses return
##########################################################################

pause()
{
    local junk
    
    printf "Press return to continue..."
    read junk
}

pkgin install -y apache ganglia-webfrontend

OS_RELEASE=`auto-os-release`
prefix=`auto-pkgsrc-prefix`

##########################################################################
#   Systemd init script
##########################################################################

# FIXME: CentOS7 only
init_script=$prefix/etc/apache.service

# selinux attempted fixes
#chcon -R -t httpd_sys_rw_content_t $ganglia_web
#setsebool -P allow_httpd_sys_script_anon_write 1
#restorecon -R -v $ganglia_web
#setsebool -P allow_httpd_anon_write=1
# FIXME: Temporary hack
# OK with pkgsrc apache24
# setenforce Permissive
# setenforce Enforcing

web_root=$prefix/share/httpd/htdocs

DATADIR=$prefix/share/cluster-admin
cp $DATADIR/WWW/global_styles.css \
    $DATADIR/WWW/centos-power.jpg \
    $DATADIR/WWW/pkgsrc.jpg \
    $web_root
chmod a+rX $web_root/*

if [ ! -e $web_root/index.php ]; then
    printf "Cluster name as it should appear on the web? "
    read name
    sed -e "s|%%HOSTNAME%%|$name|g" $DATADIR/WWW/index.php > $web_root/index.php
fi

# Just set up gmond.conf on the head node and distribute to other nodes
# gmond already enabled by cluster-setup on all nodes
if [ ! -e $prefix/etc/gmond.conf ]; then
    cp $prefix/share/examples/ganglia/gmond.conf $prefix/etc
fi

printf "Install/edit $prefix/etc/gmond.conf.\n"
pause
vi $prefix/etc/gmond.conf
chmod 644 $prefix/etc/gmond.conf

# gmetad just for head node
if [ ! -e $prefix/etc/gmetad.conf ]; then
    cp $prefix/share/examples/ganglia/gmetad.conf $prefix/etc
fi

printf "Install/edit $prefix/etc/gmetad.conf.\n"
pause
vi $prefix/etc/gmetad.conf
chmod 644 $prefix/etc/gmetad.conf

case $OS_RELEASE in
RHEL6)
    cp $prefix/share/examples/ganglia/gmetad.init.linux /etc/init.d/gmetad
    chkconfig --add gmetad
    chkconfig gmetad on       # probably redundant
    service gmetad restart
    ;;

RHEL7)
    # FIXME: ganglia pkg should create this
    mkdir -p $prefix/var/run/
    systemctl disable gmetad.service || true
    systemctl enable $prefix/share/examples/ganglia/gmetad.service
    systemctl daemon-reload
    systemctl restart gmetad.service
    ;;

*)
    printf "Unsupported os release: $OS_RELEASE\n"
    exit 1

esac
pause

# FIXME: CentOS7 only
# https://gist.github.com/blacksaildivision/199f9806dc68b2e7cf78713ae4631dfe
# FIXME: Add this to apache package?
if [ ! -e $init_script ]; then
    cat << EOM > $init_script
[Unit]
Description=The Apache HTTP Server
After=network.target

[Service]
Type=forking
ExecStart=$prefix/sbin/apachectl -k start
ExecReload=$prefix/sbin/apachectl -k graceful
ExecStop=$prefix/sbin/apachectl -k graceful-stop
PIDFile=$prefix/var/run/httpd.pid
PrivateTmp=true

[Install]
WantedBy=multi-user.target
EOM
fi

systemctl disable apache.service || true
systemctl enable $init_script || true
systemctl daemon-reload

##########################################################################
#   Hacks to apache config
##########################################################################

httpd_conf=$prefix/etc/httpd/httpd.conf
sed -i'' -e 's|DirectoryIndex index.html|DirectoryIndex index.php|' $httpd_conf

# Disable threaded MPM, conflicts with non-threaded mod_php
sed -i'' -e 's|^LoadModule mpm_event_module|#LoadModule mpm_event_module|' $httpd_conf
sed -i'' -e 's|#LoadModule mpm_prefork_module|LoadModule mpm_prefork_module|' $httpd_conf

if ! fgrep -q '/ganglia/' $httpd_conf; then

    cat << EOM >> $httpd_conf

# www/ap-php/MESSAGE
LoadModule php7_module lib/httpd/mod_php7.so
<FilesMatch \.php$>
    SetHandler application/x-httpd-php
</FilesMatch>

# www/ganglia-webfrontend/MESSAGE
Include $prefix/etc/ganglia/apache.conf
EOM

# Appears to be unnecessary
cat << EOM >> /dev/null
<Directory "$prefix/share/httpd/htdocs/ganglia/">
    Options Indexes FollowSymlinks MultiViews
    AllowOverride None
    Order allow,deny
    Allow from all
    <IfModule dir_module>
	DirectoryIndex index.php
    </IfModule>
</Directory>
EOM
fi
vi $httpd_conf

# Make sure everything is readable by apache_user
chown -Rh ${apache_user}:${apache_user} $prefix/share/ganglia/
chmod -R a+rX $prefix/share/ganglia/
systemctl restart apache.service
