#!/bin/sh -e

if [ `hostname -s` != 'login' ]; then
    printf "$0 can only be run on the primary login node.\n"
    exit 1
fi

for node in `cluster-compute-nodes`; do
    printf "Syncing slurm.conf to $node...\n"
    rsync -pog /usr/pkg-1/etc/slurm.conf ${node}:/usr/pkg-1/etc
done

slurm-sync-backup-login

