#!/bin/sh -e

if [ `hostname -s` != 'login' ]; then
    printf "$0 can only be run on the primary login node.\n"
    exit 1
fi

# Caution: 
# The line below is modified by install.sh. Be careful not to replace
# %%PREFIX%% with a hard-coded prefix from an installed script.
prefix=%%PREFIX%%

for node in `cluster-compute-nodes`; do
    printf "Syncing slurm.conf to $node...\n"
    # Caution: Be careful not to replace $prefix with a hard-coded
    # prefix from an installed script.
    rsync -pog $prefix/etc/slurm.conf ${node}:$prefix/etc
done

slurm-sync-backup-login

