#!/bin/sh -e

##########################################################################
#   Script description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2014-11-10  root        Begin
##########################################################################

usage()
{
    printf "Usage: $0 username\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 1 ]; then
    usage
fi

user_name=$1
for job in `slurm-cluster-load | sort -nr -k 1 | awk -v user_name=$user_name '$2 == user_name { print $1 }'`; do
    printf "==================\n"
    squeue -o '%6A %8u %2t %4C %3D %3h %8j %11M %N' -j $job
    printf "\nSuspend? (y/[n]/q) "
    read resp
    if [ 0$resp = 0y ]; then
	scontrol suspend $job
    elif [ 0$resp = 0q ]; then
	exit 0
    fi
    slurm-user-cores
done

