#!/bin/sh -e

usage()
{
    printf "Usage: $0 groupname [options]\n"
    printf 'All arguments are passed to the OS group add command.\n'
    exit 1
}

auto-root-check $0

if [ $# -lt 1 ] || [ `echo $1 | cut -c 1,1` = '-' ]; then
    usage
fi

group_name=$1
shift

ostype=`auto-ostype`
case $ostype in
FreeBSD)
    groupadd_cmd="pw groupadd $group_name $*"
    ;;

RHEL)
    groupadd_cmd="groupadd $* $group_name"
    ;;

*)
    printf "$0: Not yet implemented on $ostype.\n"
    exit 1

esac

# Eval here to expand before running
eval $groupadd_cmd

cluster-run "$groupadd_cmd" all
