#!/bin/sh

groupadd -g 2000 admin
cluster-run 'groupadd -g 2000 admin' all
for user in bacon jfwagner dsiercks davidc; do
    usermod -a -G admin $user
    cluster-run "usermod -a -G admin $user" all
done
tail /etc/group

