#!/bin/sh -e

##########################################################################
#   Function description:
#       Pause until user presses return
##########################################################################

pause()
{
    local junk
    
    printf "Press return to continue..."
    read junk
}


change_ip()
{
    if [ $# != 2 ]; then
	printf "Usage: change_ip old-ip new-ip\n"
	exit 1
    fi
    
    old_ip=10.1.1.$1
    new_ip=10.1.1.$2
    printf "$old_ip -> $new_ip\n"
    pause
    sed -i -e "s|$old_ip|$new_ip|g" /etc/hosts
    sed -i -e "s|$old_ip|$new_ip|g" /etc/ssh/ssh_config
    sed -i -e "s|$old_ip|$new_ip|g" /etc/dhcp/dhcpd.conf
    ssh $old_ip shutdown -r now
}

ip=115
while [ $ip -le 142 ]; do
    change_ip $ip $(($ip - 1))
    ip=$(($ip + 1))
done

ip=146
while [ $ip -le 147 ]; do
    change_ip $ip $(($ip - 4))
    ip=$(($ip + 1))
done

