#!/bin/sh

##########################################################################
#   Script description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2013-12-31  root        Begin
##########################################################################

usage()
{
    printf "Usage: $0 username\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ `hostname -s` != 'login' ]; then
    printf "$0 can only be run on the primary login node.\n"
    exit 1
fi

if [ $# != 1 ]; then
    usage
fi

user_name="$1"

# Add user and group to I/O and compute nodes
for node in `cluster-backup-login-nodes` `cluster-io-nodes` `cluster-compute-nodes`; do
    node-sync-user $node $user_name
done

