#!/bin/sh

while true; do

    clear
    cat << EOM

1.. Mount NFS shares
2.. Monitor NFS load on data.avi
3.. Monitor NFS load on raid1.avi
Q.. Quit

EOM

    printf "Selection? "
    read selection
    clear
    case $selection in
    1)
	cluster-mount-nfs-shares
	;;
    2)
	ssh data iostat -p sdb,sdc,sdd,sde -m 1
	;;
    3)
	ssh raid1 iostat -p sdb,sdc,sdd,sde -m 1
	;;
    Q|q)
	exit 0
    esac
done

