#!/bin/sh -e

if [ `hostname -s` != 'login' ]; then
    printf "$0 can only be run on the primary login node.\n"
    exit 1
fi

cluster-dist-file compute-mount-nfs /root compute 700
cluster-run '/root/compute-mount-nfs' compute

