#!/bin/sh

##########################################################################
#   Script description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2013-12-28  root        Begin
##########################################################################

usage()
{
    printf "Usage: $0 'command' backup|compute|io|all\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ `hostname -s` != 'login' ]; then
    printf "$0 can only be run on the primary login node.\n"
    exit 1
fi

if [ $# != 2 ]; then
    usage
fi

command="$1"
node_type=$2

if [ $node_type = 'io' ] || [ $node_type = 'all' ]; then
    for node in `cluster-io-nodes`; do
	printf "================================= $node =================================\n"
	ssh -t $node "$command"
    done
fi

if [ $node_type = 'compute' ] || [ $node_type = 'all' ]; then
    for node in `cluster-compute-nodes`; do
	printf "================================= $node =================================\n"
	ssh -t $node "$command"
    done
fi

if [ $node_type = 'backup' ] || [ $node_type = 'all' ]; then
    for node in `cluster-backup-login-nodes`; do
	printf "================================= $node =================================\n"
	ssh -t $node "$command"
    done
fi

