#!/bin/sh

while true; do

    clear
    cat << EOM

1.. Monitor Network load on a node
Q.. Quit

EOM

    printf "Selection? "
    read selection
    clear
    case $selection in
    1)
	printf "Node? "
	read node
	ssh $node netstat -i ib0 -c 1
	;;
    Q|q)
	exit 0
    esac
done

