#!/bin/sh -e

# Do not sync /share*.  They will be mounted directly.

rsync -av data:/root data.root
rsync -av data.root/ data2:/root
rm -rf data.root

# This causes updates to be installed.  Use cached RPMs instead?
exit
pkgs=`ssh data yum list installed | awk ' { print $1 }'`
for node in data2 raid1; do
    ssh $node yum install $pkgs
done

