#!/bin/sh -e

cd /home
for user_name in *; do
    if [ -e $user_name/.ssh ] && fgrep -q 'root@login' $user_name/.ssh/id_rsa.pub; then
	#cat $user_name/.ssh/id_rsa.pub
	rm -f $user_name/.ssh/*
	~/CentOS-cluster-admin/ssh-keygen-for-user $user_name
    fi
done

