#!/bin/sh


##########################################################################
#   Function description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2013-08-29  root        Begin
#
#   Static:
#
#   IPADDR=x.x.x.x
#   BOOTPROTO=none
#   NETMASK=255.255.255.0
#   GATEWAY=y.y.y.y
#   DNS1=y.y.y.y
#   DNS2=y.y.y.y
#   USERCTL=yes
#
#   DHCP:
#
#   BOOTPROTO=dhcp
#
#   Both:
#
#   DEVICE=eth0
#   HWADDR=leave alone
#   TYPE=ethernet
#   UUID=leave alone
#   ONBOOT=yes
#   NM_CONTROLLED=yes
#
##########################################################################

nic_config()
{
    if [ $# != 2 ]; then
	printf "Usage: $0 interface hostname\n"
	exit 1
    fi
    interface=$1
    hostname=$2

    # Get hostname
    default_local_hostname="$hostname-$interface.local"
    case $NODE_TYPE in
    'head'|'io')
	local_hostname=`auto-ask local-hostname-$interface "Local hostname for $interface?" $default_local_hostname`
	;;
    'compute')
	local_hostname=$default_local_hostname    
	;;
    esac
    local_short_hostname=`echo $local_hostname | cut -d '.' -f 1`
    
    # Edit config file for this interface
    file=/etc/sysconfig/network-scripts/ifcfg-$interface

    # Delete old entries
    sed -i'' -e '/IPADDR/d' $file
    sed -i'' -e '/BOOTPROTO/d' $file
    sed -i'' -e '/NETMASK/d' $file
    sed -i'' -e '/GATEWAY/d' $file
    sed -i'' -e '/DNS1/d' $file
    sed -i'' -e '/DNS2/d' $file
    
    # FIXME: Add DHCP option
    dhcp=`auto-ask dhcp 'Use DHCP?' n`
    if [ $dhcp = 'y' ]; then
	cat << EOM >> $file
BOOTPROTO=dhcp
EOM
    else
	# Get IP address
	current_ip=`ifconfig $interface | awk '$1 == "inet" { print $2 }' | awk -F : ' { print $2 }'`
	printf "Current IP = $current_ip\n"
	if [ 0$current_ip != 0 ]; then
	    default_local_ip=$current_ip
	fi
	local_ip=`auto-ask local-ip-$interface "Local IP address for $interface?" $default_local_ip`
    
	# FIXME: Do not hard-code assumptions about compute nodes
	# For compute nodes: NETMASK, GATEWAY, DNS1, DNS2 are configured in /etc/dhcp/dhcpd.conf
    
	netmask=`auto-ask netmask-$interface "Net mask for $interface" 255.255.0.0`
	default_gateway=`echo $local_ip | awk -F '.' ' { printf("%s.%s.%s.1",$1,$2,$3); }'`
	gateway=`auto-ask gateway-$interface "Gateway for $interface" $default_gateway`
	dns1=`auto-ask dns1 "IP of primary DNS server?" $default_gateway`
	dns2=`auto-ask dns2 "IP of secondary DNS server?" 0.0.0.0`

	# Add new entries
	cat << EOM >> $file
IPADDR=$local_ip
NETMASK=$netmask
GATEWAY=$gateway
DNS1=$dns1
DNS2=$dns2
BOOTPROTO=none
EOM
	# Add IP's and names to hosts file
	line
	printf "Updating /etc/hosts...\n"
	# auto-append-line is not installed yet
	if ! fgrep -q $local_ip /etc/hosts; then
	    printf "$local_ip\t$local_hostname\t$local_short_hostname" >> /etc/hosts
	fi
    fi


    if false; then
	# Compute node network setup
	sed -i '2iDHCP_HOSTNAME='"\"$hostname\""' ' $file
	sed -i '/IPV6INIT="yes"/ c\IPV6INIT="no"' $file
	sed -i '/NM_CONTROLLED="yes"/ c\NM_CONTROLLED="no"' $file
	sed -i '/ONBOOT="no"/ c\ONBOOT="yes"' $file
	sed -i '/UUID/ c\' $file
	HOSTIP=`ifconfig $interface | awk '$1 == "inet" {print $2}' | cut -d ":" -f 2`
	SUBNET=`ifconfig $interface | awk '$1 == "inet" {print $2}' | cut -d ":" -f 2 | cut -d "." -f 1-3`.0
	NETMASK=`ifconfig $interface | awk '$1 == "inet" {print $4}' | cut -d ":" -f 2`
	HWADDR=`ifconfig $interface | awk '$2 == "Link" {print $5}'`

	if [ ! `grep $NETMASK $file | awk '{print $1}'` ]; then
	    sed -i '4iNETMASK='"$NETMASK"' ' $file
	fi
	if [ ! `grep $SUBNET $file | awk '{print $1}'` ]; then
	    sed -i '4iNETWORK='"$SUBNET"' ' $file
	fi
	if [ ! `grep $HOSTIP $file | awk '{print $1}'` ]; then
	    sed -i '4iIPADDR='"$HOSTIP"' ' $file
	fi
	if [ ! `grep $HWADDR 4file | awk '{print $1}'` ]; then
	    sed -i '4iHWADDR='"$HWADDR"' ' $file
	fi
    fi
    
    # FIXME: Distribute new entry to all nodes when compute node is added
}


##########################################################################
#   Function description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2013-12-10  root        Begin
##########################################################################

network_config()
{
    # Configure network
    line
    net_config=`auto-ask net-config 'Configure network?' n`
    if [ $net_config != 'y' ]; then
	return
    fi
    default_hostname=`hostname`
    hostname=`auto-ask local-hostname "Hostname?" $default_hostname`
    
    sed -i'' -e '/HOSTNAME/d' /etc/sysconfig/network
    # auto-admin is not yet installed, so do this manually
    if ! fgrep -q HOSTNAME /etc/sysconfig/network; then
	printf "HOSTNAME=$hostname\n" >> /etc/sysconfig/network
    fi
    
    # Configure local interface and add to hosts file
    # Probe and ask for viable public network interface (NB: reserve eth0/em0 for compute nodes subnet)
    
    niclist=""
    for n in `ifconfig | cut -c 1-6 | sort | uniq`
    do
	if [ $n != "lo" ]; then
	niclist=$niclist,$n
    fi
    done
    niclist=`echo $niclist | sed -e 's/,//'` 
    defnic=`echo $niclist | cut -d "," -f1`
    printf "Available NICs are: $niclist.\n"
    nic=`auto-ask nic "Interface?" $defnic`
    nic_config $nic $hostname
    
    service network restart
    return 0
}

