#!/bin/sh -e

if [ $# = 0 ]; then
    users=`awk -F : '$1 ~ "_a" { print $1 }' passwd.old`
else
    users="$@"
fi

for user in $users; do
    user_name=${user%_a}
    
    if ! fgrep -q $user_name /etc/passwd; then
	# Get info from old password and group files
	user_id=`awk -F : -v user=$user '$1 == user { print $3 }' passwd.old`
	group_id=`awk -F : -v user=$user '$1 == user { print $4 }' passwd.old`
	group_name=`awk -F : -v group_id=$group_id '$3 == group_id { print $1 }' group.old`
	group_name=${group_name%_a}
	gecos=`awk -F : -v user=$user '$1 == user { print $5 }' passwd.old`
	home=`awk -F : -v user=$user '$1 == user { print $6 }' passwd.old`
	home=${home%_a}
	shell=`awk -F : -v user=$user '$1 == user { print $7 }' passwd.old`
	
	# Create user and group
	printf "\n$user_name $user_id $group_id:$group_name $gecos $home $shell\n\n"
	printf "Restore $user_name? [n] "
	read restore
	if [ 0$restore = 0y ]; then
	    # FIXME: cluster-useradd should handle this
	    groupadd -g $group_id $group_name || true
	    cluster-useradd $user_name $user_id $group_id "$gecos" $home $shell
	fi
    fi
done

