#!/bin/sh

cd /home
for user in *; do
    printf "$user\n"
    old_dir=/sharedapps/Old-Avi/Backup/hd1/home/${user}_a
    if [ -e $old_dir ] && [ ! -e $user/Old-Avi ] && [ ! -L $user/Old-Avi ]; then
	printf "Restoring $user..\n"
	mkdir -p $user/Old-Avi
	rm -rf $old_dir/.ssh
	rsync -av --delete $old_dir/ $user/Old-Avi
    fi
    
    if [ -e $user/Old-Avi ]; then
	group=`awk -F : -v user_name=$user_name '$1 == user_name { print $4 }' /etc/passwd`
	chown -Rh ${user}:$group $user/Old-Avi
	chmod -R o-rwx,g-w $user/Old-Avi
	if [ -e $user/Old-Avi/Data ]; then
	    cp -d $user/Old-Avi/Data $user
	fi
	if [ -e $user/Old-Avi/data ]; then
	    cp -d $user/Old-Avi/data $user
	fi
    fi
done

