#!/bin/sh -e

case `uname` in
    FreeBSD)
	os='FreeBSD'

	if [ -z $PREFIX ]; then
	    PREFIX=/usr/local/cluster-admin
	fi
	;;
    Linux)
	#
	if [ -e /etc/redhat-release ]; then
	    os='CentOS'
	else
	    printf "Only RHEL-based Linux is supported.\n"
	    exit 1
	fi

	if [ -z $PREFIX ]; then
	    PREFIX=/usr/local
	fi
	DATADIR=$PREFIX/share/cluster-admin
	mkdir -p $DATADIR
	cp CentOS/WWW/* $DATADIR
	;;
    *)
	printf "Unsupported OS: `uname`\n"
	exit 1
esac

set -x
for dir in bin sbin libexec; do
    mkdir -p ${STAGEDIR}${PREFIX}/$dir
done
rm -f ${STAGEDIR}${PREFIX}/sbin/cluster-*
rm -f ${STAGEDIR}${PREFIX}/bin/cluster-*
cp $os/Sys-scripts/* ${STAGEDIR}${PREFIX}/sbin
cp $os/User-scripts/* ${STAGEDIR}${PREFIX}/bin
cp Common/Sys-scripts/* ${STAGEDIR}${PREFIX}/sbin
cp Common/User-scripts/* ${STAGEDIR}${PREFIX}/bin
chmod 750 ${STAGEDIR}${PREFIX}/sbin/*
chmod 755 ${STAGEDIR}${PREFIX}/bin/*

cp Common/*.awk ${STAGEDIR}${PREFIX}/libexec
sed -e "s|add-gecos.awk|${PREFIX}/libexec/add-gecos.awk|g" \
    Common/Sys-scripts/slurm-usage-report \
    > ${STAGEDIR}${PREFIX}/sbin/slurm-usage-report
sed -e "s|cluster-admin.conf|${PREFIX}/etc/cluster-admin.conf|g" \
    Common/Sys-scripts/cluster-admin.conf \
    > ${STAGEDIR}${PREFIX}/sbin/cluster-admin.conf

