#!/bin/sh -e

for script in */*-scripts/*; do
    ape $script
    cat << EOM

1.. Remove
2.. Deprecate

EOM
    read action
    case 0$action in
    01)
	svn remove $script
	;;
    
    02)
	old=$(dirname $(dirname $script))/Old
	mkdir -p $old
	svn mv $script $old
	;;
    
    *)
	;;
    
    esac
done
