#!/bin/sh -e

yum install -y subversion

# Install pkgsrc
if [ ! -e /usr/pkg-1 ]; then
    ./pkgsrc-setup
    . /usr/pkg-1/etc/shrc
    printf ". /usr/pkg-1/etc/shrc\n" >> /root/.bashrc
fi

# Install jb-wip, ape, bench
cd /usr/pkgsrc-1
if [ ! -e jb-wip ]; then
    svn co svn+ssh://bacon@jbacon.dyndns.org/home/bacon/SVN/jb-wip
fi

if [ ! -e /usr/pkg-1/bin/ape ]; then
    cd jb-wip/ape
    bmake install
fi

if [ ! -e /usr/pkg-1/bin/bench ]; then
    cd ../bench
    bmake install
fi

