#!/bin/sh -e

##########################################################################
#   Script description:
#       Check age of password
#
#   History:
#   Date        Name        Modification
#   2018-12-17  J Bacon     Begin
##########################################################################

usage()
{
    printf "Usage: $0 [user-name]\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if is-login-node; then
    case $# in
    0)
        user_name=`whoami`
        ;;
    
    1)
        user_name=$1
        ;;
    
    *)
        usage
        ;;
    
    esac

    pw_age_dir=/usr/local/cluster/pw-age
    pw_age_file=$pw_age_dir/$user_name
    max_pw_age=`awk '{ print $1 }' $pw_age_file`
    last_pw_change=`awk '{ print $2 }' $pw_age_file`
    today=`date +%s`
    today=$(($today / 3600 / 24))
    pw_age=$(($today - $last_pw_change))
    printf "Max password age: $max_pw_age  Days since last change: $pw_age\n"
 
    if [ `whoami` = $user_name ] && [ $pw_age -ge $max_pw_age ]; then
	printf "Your password is expired.\n"
	cluster-passwd
    fi
else
    printf "Please run $0 on the login node.\n"
fi
