#!/bin/sh

status=0
printf "%-20s %-10s %s\n" "Host" "Ping" "SSH"
for node in `cluster-backup-login-nodes` `cluster-io-nodes` `cluster-compute-nodes`; do
    printf "%-20s " $node
    if ! ping -c 1 $node > /dev/null 2>&1; then
	printf "%-10s %s\n" "Failed" "-"
	status=1
    else
	printf "%-10s " "OK"
	if ! ssh $node hostname > /dev/null 2>&1; then
	    printf "Failed\n"
	    status=1
	else
	    printf "OK\n"
	fi
    fi
done
exit $status

