#!/bin/sh -e

# Return 0 status regardless
# The new standard is compute-[0-9]+, .*raid-[0-9]+, and login-[0-9]+
# for all nodes.
# ^data and raid.* are here to allow legacy names on older clusters
awk '$2 ~ "^data" || $2 ~ "raid.*[0-9]+\\." { print $3 }' \
    /etc/hosts | fgrep -v ib0 || true

