#!/bin/sh -e

# Return 0 status regardless
# The standard is compute-[0-9]+, .*raid-[0-9]+, and login-[0-9]+
# for all nodes.
awk '$2 ~ "raid-[0-9]+\\." { print $3 }' /etc/hosts \
    | egrep -ve '-ib0|-mgmt|-hpc|-aux' || true

