#!/bin/sh

##########################################################################
#   Script description:
#       Conveniently run top on a cluster node
#       
#   History:
#   Date        Name        Modification
#   2013-05-01  Jason Bacon Begin
##########################################################################

usage()
{
    cat << EOM

Usage: $0 complete-node-name|compute-node-index

If the argument does not begin with compute-, raid-, vis-, or login-,
then compute- is automatically prepended.

Example:
    node-iostat 002         # same as node-iostat compute-002
    node-iostat compute-002
    node-iostat 256g-004
    node-iostat compute-256g-001
    node-iostat raid-01

EOM
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 1 ]; then
    usage
fi

node=$1
shift
if ! echo $node | egrep -q '^compute-|^raid-|^vis-|^login-'; then
    node=compute-$node
fi

case $(auto-ostype) in
FreeBSD)
    if ssh $node mount | fgrep -q 'zfs,'; then
	ssh -t $node zpool iostat 1
    else
	ssh $node iostat 1
    fi
    ;;

RHEL)
    ssh $node iostat -dm 1
    ;;

*)
    printf "$0: Not supported on $(auto-ostype).\n"
    exit 1
    ;;
esac
