#!/bin/sh

cat << EOM

********************************** NOTE ***********************************

You can use additional "srun" flags with slurm-shell to allocate more
cores or more memory for this session, or alter the allocation in any
other way supported by srun.

Example:

slurm-shell --ntasks=4 --mem=6g

Run "man srun" for a complete list of options.

********************************* WARNING *********************************

Interactive jobs run in this manner may be terminated at any moment if
security updates on the login node require a reboot.

The ability to run interactive jobs is provided as a convenience with no
guarantees.

HPC clusters are intended for running batch jobs and are not well suited
for running interactive applications in general.

Users who require fast graphical sessions or reliable interactive sessions
are advised to use a desktop computer rather than an HPC cluster.

***************************************************************************

EOM

# A simpler way
srun --mem-per-cpu=3000 --ntasks=1 --pty --preserve-env $@ $SHELL -l

# An overcomplicated way?
# salloc -n1 srun -n1 -N1 --pty --preserve-env $SHELL -l

