#!/bin/sh

if [ "0$1" = 0-a ]; then
    partitions=`sinfo -h -o '%R'`
else
    partitions=`sinfo -h -o '%R' | grep -v -e -nice`
fi

for partition in $partitions; do
    allocated=`sinfo -h -p $partition -o '%C' | awk -F '/' ' { print $1 }'`
    total=`sinfo -h -p $partition -o '%C' | awk -F '/' ' { print $4 }'`
    load=$((allocated * 100 / total))
    printf "\n%s: %s%%\n" $partition $load
    sinfo -p $partition -o '%C'
done

