#!/bin/sh -e

##########################################################################
#   Script description:
#       Monitor processes for a given job
#       
#   History:
#   Date        Name        Modification
#   2020-02-03  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0 job-ID\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 1 ]; then
    usage
fi
job_id=$1

for node in $(lpjs jobs | awk -v job_id=$job_id '$1 == job_id { print $9 }'); do
    echo $node
    spcm-node-top $node
done
