#!/bin/sh

##########################################################################
#   Script description:
#       Conveniently run top on a cluster node
#       
#   History:
#   Date        Name        Modification
#   2013-05-01  Jason Bacon Begin
##########################################################################

usage()
{
    cat << EOM

Usage: $0 complete-spcm-node-name|compute-spcm-node-index

If the compute-<argument> is a valid compute node host name, then compute-
is automatically prepended.

Example:
    spcm-top 002         # same as spcm-top compute-002
    spcm-top compute-002
    spcm-top 256g-004
    spcm-top compute-256g-001
    spcm-top raid-01

EOM
    exit 1
}

##########################################################################
#   Function description:
#       Pause until user presses return
##########################################################################

pause()
{
    local junk
    
    printf "Press return to continue..."
    read junk
}


##########################################################################
#   Main
##########################################################################

if [ $# != 1 ]; then
    usage
fi

node=$1
shift
# Convert 001 to compute-001.domain if possible
temp="$(awk -v hostname=$node '$3 == "compute-" hostname { print $2 }' /etc/hosts)"
if [ -n "$temp" ]; then
    node=$temp
fi
if [ 0$(spcm-node-type compute-$node) = 0compute ]; then
    node=compute-$node
fi

if ! (awk '{ print $2 }' /etc/hosts | fgrep -x $node || \
    awk '{ print $3 }' /etc/hosts | fgrep -x $node); then
    printf "$0: $node not found in /etc/hosts.\n"
    exit 1
fi

printf "Press 'q' to quit\n"
pause

ssh -t $node top $*
