#!/bin/sh

##########################################################################
#   Script description:
#       Conveniently run top on a cluster node
#       
#   History:
#   Date        Name        Modification
#   2013-05-01  Jason Bacon Begin
##########################################################################

usage()
{
    cat << EOM

Usage: $0 complete-node-name|compute-node-index

If the argument does not begin with compute-, raid-, vis-, or login-,
then compute- is automatically prepended.

Example:
    topnode 002         # same as topnode compute-002
    topnode compute-002
    topnode 256g-004
    topnode compute-256g-001
    topnode raid-01

EOM
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 1 ]; then
    usage
fi

node=$1
shift
if ! echo $node | egrep -q '^compute-|^raid-|^zfs-|^vis-|^login-'; then
    node=compute-$node
fi
ssh -t $node top $*
