#!/bin/sh

##########################################################################
#   Script description:
#       Conveniently run top on a cluster node
#       
#   History:
#   Date        Name        Modification
#   2013-05-01  Jason Bacon Begin
##########################################################################

usage()
{
    cat << EOM

Usage: $0 node-name|compute-node-index

Example:
    topnode 002
    topnode compute-002
    topnode raid-01

EOM
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 1 ]; then
    usage
fi

node=$1
shift
if ! echo $node | fgrep -q -e -; then
    node=compute-$node
fi
ssh -t $node top $*
