#!/bin/sh

##########################################################################
#   Script description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2013-07-30  Charlie &   Begin
##########################################################################

usage()
{
    printf "Usage: $0 ip-address\n"
    exit 64 # From sysexits.h
}

##########################################################################
#   Main
##########################################################################

#
if [ $# != 1 ]; then
    usage
fi

ip=$1
work_dir='/usr/pkg-1/share/denyhosts/data'

# Stop DenyHosts
service denyhosts stop

# Remove the IP address from /etc/hosts.deny
sed -i "/$ip/d" /etc/hosts.denyhosts

# Edit WORK_DIR/hosts and remove the lines containing the IP address. Save the file.
sed -i "/$ip/d" $work_dir/hosts

# Edit WORK_DIR/hosts-restricted and remove the lines containing the IP address. Save the file.
sed -i "/$ip/d" $work_dir/hosts-restricted

# Edit WORK_DIR/hosts-root and remove the lines containing the IP address. Save the file.
sed -i "/$ip/d" $work_dir/hosts-root

# Edit WORK_DIR/hosts-valid and remove the lines containing the IP address. Save the file.
sed -i "/$ip/d" $work_dir/hosts-valid

# Edit WORK_DIR/user-hosts and remove the lines containing the IP address. Save the file.
sed -i "/$ip/d" $work_dir/users-hosts

# Start DenyHosts
service denyhosts start

