#!/bin/sh -e


##########################################################################
#   Function description:
#       Pause until user presses return
##########################################################################

pause()
{
    local junk
    
    printf "Press return to continue..."
    read junk
}

# http://fedir.github.io/lessons/2013/03/26/NFS-debug/
# http://www.sysxperts.com/home/announce/vmdirtyratioandvmdirtybackgroundratio

# http://www.slashroot.in/how-do-linux-nfs-performance-tuning-and-optimization
# rsize,wsize: no effect
# async: 15-20% improvement

sync

# Used for queuing NFS requests.  Should be increased to accommodate
# increased number of NFS server daemons.  Increasing seems to help
# random seeks.  Not much effect on write performance.
mem=124928  # default.
mem=1048576
mem=4194304
sysctl net.core.rmem_max=$mem
sysctl net.core.rmem_default=$mem
sysctl net.core.wmem_max=$mem
sysctl net.core.wmem_default=$mem

# Percent of memory to use before background flushing kicks in.
# This should be small, so that background flushing is utilized
# as much as possible.  Otherwise, the server may be twiddling its
# thumbs while it could be writing data to disk.
#sysctl vm.dirty_background_ratio=2
#sysctl vm.dirty_background_bytes=1073741824
#sysctl vm.dirty_background_bytes=268435456
#sysctl vm.dirty_background_bytes=134217728
#sysctl vm.dirty_background_bytes=67108864

#bytes=1073741824
bytes=268435456
#bytes=134217728
#bytes=67108864

sysctl vm.dirty_background_bytes=$bytes
# FIXME: Remove old entry from sysctl.conf
auto-append-line vm.dirty_background_bytes=$bytes /etc/sysctl.conf $0

# Percent of memory to use before I/O is blocked until flush is complete.
# On a dedicated file server, this should be high, to utilize
# available memory for disk buffering.  Leave some for read caching
# and other OS functions.  On other computers that need
# memory to run applications, it should be kept fairly small.

dirty_ratio=80
sysctl vm.dirty_ratio=$dirty_ratio
auto-append-line vm.dirty_ratio=$dirty_ratio /etc/sysctl.conf $0
#vi /etc/sysconfig/nfs
#service nfs restart

vi /etc/sysctl.conf

iostat -dm 1

