#!/bin/sh -e

sync

mem=124928  # default
#mem=1048576
sysctl net.core.rmem_max=$mem
sysctl net.core.rmem_default=$mem
sysctl net.core.wmem_max=$mem
sysctl net.core.wmem_default=$mem

umount /fasttemp1
vi /etc/fstab
mount /fasttemp1

cd /fasttemp1
ls
rm -f bench.tempfile
sync
bench

