#!/bin/sh -e

usage()
{
    printf "Usage: $0 groupname [options]\n"
    printf 'All arguments are passed to "pw groupadd"\n'
    exit 1
}

if [ `whoami` != root ]; then
    printf "$0 must be run as root.\n"
    exit 1
fi

if [ $# -lt 1 ] || [ `echo $1 | cut -c 1,1` = '-' ]; then
    usage
fi

group_name=$1
groupadd_cmd="pw groupadd $*"

# Eval here to expand before running
eval $groupadd_cmd

cluster-run "$groupadd_cmd" all

