#!/bin/sh -e

##########################################################################
#   Script description:
#       Set up a FreeBSD condor node
#
#   Arguments:
#       One or more of
#           manager
#           submit
#           execute
#
#   Returns:
#       Standard codes
#   History:
#   Date        Name        Modification
#   2012-11-02  J Bacon     Begin
##########################################################################

usage()
{
    printf "Usage: $0 [manager] [submit] [execute]\n"
    exit 1
}

##########################################################################
#   Main
##########################################################################

#
if [ $# -lt 1 ]; then
    usage
fi

for arg in $@; do
    # 
    case $arg in
    manager)
	manager=1
	;;
    submit)
	submit=1
	;;
    execute)
	execute=1
	;;
    *)
	usage
	;;
    esac
done

export AUTO_BUILD_FROM_SOURCE='fall-back'

# Install condor
# auto-install-packages sysutils/condor

# Edit condor_config.local

# Install packages
# carve cblas clp dcdflib eigen3 givaro ldouble libflame matrix mtl
# matharray octave fityk
# qhull conflicts with qhull5

for port in math/qhull science/netcdf; do
    if auto-package-installed $port; then
	pkg_delete /var/db/pkg/$(basename $port)*
    fi
done

# Netcdf3-ftn conflicts with netcdf and some packages will install netcdf as a
# prereq. Pre-install netcdf3-ftn and it will satisfy the prereqs.
# Note: netcdf is v3, netcdf-ftn is v4
auto-install-packages science/netcdf3-ftn

auto-install-packages devel/cmake
if [ ! -e /usr/ports/math/eigen3 ]; then
    auto-update-port-framework -c math/eigen3
fi
auto-install-packages math/eigen3

export AUTO_BUILD_FROM_SOURCE='fall-back'

if [ x$execute = x1 ]; then
    # Math
    # Problem: gri installs netcdf3 as a prereq
    for port in R ann arpack arpack++ bihar blas blitz++ \
	ccmath cgal chaco cln crlibm diehard \
	dieharder djbfft eispack elmer-umfpack fann fflas-ffpack \
	fftw3 freefem \
	fxt glpk gmm++ gmp gmp-ecm gnuplot goblin \
	gretl gsl ised itl jakarta-commons-math jama \
	jtransforms jts kktdirect lapack lapack++ lapack95 lapacke laspack \
	lensnns levmar libR libRmath libjbigi liblbfgs libmath++ \
	libneural libocas liborigin libqalculate libranlip libtommath libtsnnls \
	linpack lll_spect lp_solve lrng ltl ltl2ba matio mcmc-jags metis \
	miracl mpc mpfr msieve mtrxmath newmat ntl octave \
	parmgridgen pecl-big_int pecl-bitset pecl-stats ploticus primegen \
	prng pspp qd qhull5 qrupdate randlib rngstreams slatec spblas \
	spooles suitesparse superlu taucs tetgen tomsfastmath triangle trlan \
	tvmet unuran wfmath xblas xlapack
    do
	auto-install-packages math/$port
    done

    # Science
    # cdcl, dcl install fails on 8.3
    # cdo requires netcdf4
    # dtiquery has download restrictions
    for port in \
	afni bddsolve bft bodr brian buddy cdf \
	cgnslib checkmol chemical-mime-data chemtool chemtool-devel clhep \
	colt crf++ devisor ecs elmer-eio elmer-hutiter \
	elmer-matc elmer-meshgen2d elmergrid epte euler fastcap \
	fasthenry felt fvm g3data gchemutils gdis getdp \
	ghemical ghmm gramps gromacs gsmc \
	gwyddion harminv \
	hs-bio libghemical libint libkml liblinear liboglappth\
	libquantum libsvm mol2ps mpqc \
	omnetpp openbabel
    do
	auto-install-packages science/$port
    done
fi

