#!/bin/sh

if [ `whoami` != "root" ]; then
    printf "$0 must be run by root.\n"
    exit 1
fi

pause()
{
    local junk
    
    printf "Press return to continue..."
    read junk
}


while true; do
    clear
    cat << EOM

			    **********************
			    * Cluster Admin Menu *
			    **********************

    1.. LSF menu
    2.. Dell OpenManage menu
    3.. RAID menu
    4.. Shut down cluster
    5.. Add a user account
    6.. Update firewall rules
    7.. Generate DSET report on hd2 (for Dell support)
    8.. Find stray processes
    9.. Connect to iDrac on a compute node (Caution: runs firefox as root)
    Q.. Quit
EOM
    
    read resp
    if [ 0$resp = 0q ]; then
	exit 0
    fi
    
    case $resp in
    1)
	lsf-admin
	;;
    2)
	om-admin
	;;
    3)
	raid-admin
	;;
    4)
	# /usr/sbin/cluster-shutdown
	# Written by X-ISS
	printf "Are you sure you want to shut down the cluster? (yes/no) "
	read resp
	if [ 0$resp = 0yes ]; then
	    cluster-shutdown
	fi
	;;
    5)
	cluster-adduser
	pause
	;;
    6)
	printf "Editing head node iptables.\n"
	pause
	vi /etc/cfm/installer-rhel5.3-5-x86_64/etc/sysconfig/iptables
	# Copy now so that the new table will be loaded on the next reboot
	# cfmsync runs AFTER the old sysfiles are loaded
	cp /etc/cfm/installer-rhel5.3-5-x86_64/etc/sysconfig/iptables /etc/sysconfig
	
	printf "Editing I/O node iptables.\n"
	pause
	vi /etc/cfm/IO-rhel5.3-5-x86_64/etc/sysconfig/iptables
	# Copy now so that the new table will be loaded on the next reboot
	# cfmsync runs AFTER the old sysfiles are loaded
	scp /etc/cfm/IO-rhel5.3-5-x86_64/etc/sysconfig/iptables hd2:/etc/sysconfig

	# Stages new tables for use after second reboot
	cfmsync -f

	printf "Restarting firewall daemons.\n"
	printf "This may momentarily disrupt network connections.  Continue? (y/n) "
	read resp
	if [ 0"$resp" = 0y ]; then
	    /etc/init.d/iptables restart
	    ssh hd2 /etc/init.d/iptables restart
	fi
	pause
	;;
    7)
	#ssh -t hd2 dellsysteminfo
	#mkdir /root/hd2
	#scp 'hd2:/root/DSET_Report*' /root/hd2
	#printf "DSET report saved in /root/hd2\n"
	cat << EOM
This option is not currently working.  For some reason,

    ssh hd2 dellsysteminfo
    
does not produce the same results as running

    dellsysteminfo

from an interactive shell on hd2.

Log into hd2 and run "dellsysteminfo" as root from the command line.
The report will be in DSET_Report*.

Move the report file to avi-admin/Incidents.  If this is a new failure,
create a new folder under Incidents, following the naming scheme of
the other folders already there.
EOM
	pause
	;;
    8)
	printf "Username? "
	read user_name
	find-strays $user_name
	pause
	;;
    9)
	printf "Node number? (e.g. 1-10) "
	read node
	idrac-node $node
	pause
	;;
    *)
	;;
    esac
done

