#!/bin/sh -e

if [ $# != 1 ]; then
    printf "Usage: $0 package-name\n"
    exit 1
fi

if [ `whoami` != root ]; then
    printf "$0 must be run as root.\n"
    exit 1
fi

cache_dir=`cluster-pkgdir`
env PKG_CACHEDIR=$cache_dir pkg upgrade -y

pkg=$1
cluster-run "env PKG_CACHEDIR=$cache_dir cluster-local-pkg-install $pkg"

auto-append-line $pkg $pkg /usr/local/cluster/packages.txt nocomment

