#!/bin/sh

##########################################################################
#   Script description:
#       Add a user to a group on all nodes
#
#   Arguments:
#       $1 = group
#       $2 = user
#
#   History:
#   Date        Name        Modification
#   2013-06-09  Charlie &   Begin
##########################################################################

usage()
{
    printf "Usage: $0 group user\n"
    exit 1
}

##########################################################################
#   Main
##########################################################################

if [ $# != 2 ]; then
    usage
fi

group=$1
user=$2

pw groupmod $group -m $user
cluster-run "pw groupmod $group -m $user"

