#!/bin/sh -e

printf "Updating ssh_config on head...\n"
cluster-update-ssh_config
for node in `cluster-compute-nodes`; do
    printf "Updating ssh_config on $node...\n"
    ssh $node cluster-update-ssh_config
done

