# Generated by pkgsrc-setup
if ! echo $PATH | fgrep -q /sharedapps/pkg-1; then
    PKGSRC=/sharedapps/pkg-1; export PKGSRC
    PATH=$PKGSRC/bin:$PKGSRC/sbin:$PATH; export PATH
    MANPATH=$PKGSRC/man:/usr/local/share/man:/usr/share/man/overrides:/usr/share/man/en:/usr/share/man; export MANPATH
    PKGSRC_INCLUDE=$PKGSRC/include; export PKGSRC_INCLUDE
    PKGSRC_LIB=$PKGSRC/lib; export PKGSRC_LIB
    MODULEPATH=${MODULEPATH}:$PKGSRC/etc/modules; export MODULEPATH
    # Avoid using LD_LIBRARY_PATH if possible
    # LD_LIBRARY_PATH=${PKGSRC_LIB}:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH
fi
