#!/bin/sh

os_type=`auto-ostype`
case $os_type in
FreeBSD)
    cmd='rmuser -y'
    ;;
RHEL)
    cmd='userdel -r'
    ;;
*)
    printf "Unsupported OS: $os_type\n"
    exit 1
    ;;
esac

if [ `whoami` != root ]; then
    printf "$0 must be run as root.\n"
    exit 1
fi

if [ $# != 1 ]; then
    printf "Usage: $0 username\n"
    exit 1
fi

user_name=$1

printf "Are you sure you want to remove user $user_name? yes/[no] "
read resp
if [ 0$resp = 0'yes' ]; then
    printf "Save home directory? [yes]/no "
    read save_home
    if [ x$save_home != xno ]; then
	# Save home dir from removal by rmuser -y
	mv /home/$user_name /home/$user_name.save
    fi

    case $os_type in
    FreeBSD)
	$cmd $user_name
	;;
    RHEL)
	$cmd $user_name
	;;
    *)
	;;
    esac
    
    # Group should be removed by rmuser, but it isn't!
    cluster-run -c "$cmd $user_name" all
fi

