#!/bin/sh -e

##########################################################################
#   Script description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2017-03-31  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0 username new_group|new-gid [directory ...]\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# -lt 2 ]; then
    usage
fi

if [ `whoami` != 'root' ]; then
    printf "$0 can only be run by root.\n"
    exit 1
fi

if ! cluster-check-cron-updates; then
    exit 0
fi

user_name=$1
new_group=$2
shift
shift

# Verify that all dirs exits before changing anything!
dirs="$@"
for dir in $dirs; do
    if [ ! -e $dir ]; then
	printf "$0: ${dir}: No such file or directory.\n"
	exit 1
    fi
done

auto-change-primary-group $user_name $new_group $dirs
cluster-run "auto-change-primary-group $user_name $new_group" backup io vis compute
# FIXME: Should /usr/local/cluster be hard-coded?
chgrp $new_group /usr/local/cluster/pw-age/$user_name
