#!/bin/sh -e

##########################################################################
#   Script description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2016-05-06  root        Begin
##########################################################################

usage()
{
    printf "Usage: $0 [backup|compute|io node [... node]]\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

case $# in
0)
    compute_nodes=`cluster-compute-nodes`
    backup_nodes="`cluster-backup-login-nodes`"
    other_nodes="`cluster-io-nodes` `cluster-vis-nodes`"
    ;;
1)
    usage
    ;;
*)
    case $1 in
    backup)
	shift
	backup_nodes="$@"
	compute_nodes=""
	other_nodes=""
	;;
    
    io|vis)
	shift
	backup_nodes=""
	compute_nodes=""
	other_nodes="$@"
	;;
    
    compute)
	shift
	backup_nodes=""
	compute_nodes="$@"
	other_nodes=""
	;;
    
    *)
	usage
	;;
    esac
esac

# Caution: 
# The line below is modified by install.sh. Be careful not to replace
# %%PREFIX%% or %%SRC_PREFIX%% with a hard-coded prefix from an installed
# script.
prefix=%%PREFIX%%
src_prefix=%%SRC_PREFIX%%

auto-clean-pkgsrc $src_prefix

# Use wildcards in --exclude patterns, as full prefix does not work and this
# keeps things simple.

# Backup login nodes get everything except logs
for node in $backup_nodes; do
    printf "$node...\n"
    if ! rsync -av --delete \
	--exclude '*/var/*/munge' \
	$prefix $src_prefix ${node}:/usr; then
	failed_nodes="$failed_nodes $node"
    else
	ssh $node ln -sf $prefix/etc/pkgsrc.\*sh /etc/profile.d
    fi
done

# cluster-passwd can only be run on the login node
for node in $other_nodes; do
    printf "$node...\n"
    if ! rsync -av --delete \
	--exclude '*/var/*/munge' \
	--exclude '*/bin/cluster-passwd' \
	$prefix $src_prefix ${node}:/usr; then
	failed_nodes="$failed_nodes $node"
    else
	ssh $node ln -sf $prefix/etc/pkgsrc.\*sh /etc/profile.d
    fi
done

# cluster-passwd can only be run on the login node
for node in $compute_nodes; do
    printf "$node...\n"
    if ! rsync -av --delete \
	--exclude '*/var/*/munge' \
	--exclude '*/bin/cluster-passwd' \
	$prefix ${node}:/usr; then
	failed_nodes="$failed_nodes $node"
    else
	ssh $node ln -sf $prefix/etc/pkgsrc.\*sh /etc/profile.d
    fi
done

if [ ! -z "$failed_nodes" ]; then
    printf "Unable to sync the following nodes: %s\n" "$failed_nodes"
fi
