#!/bin/sh -e

auto-root-check $0

set +e

if ! cluster-check-cron-updates; then
    exit 0
fi

service gmetad restart
service gmond restart

# gmond doesn't restart unless -n is used here.  Why?
cluster-run -c -n 'service gmond restart' all

