#!/bin/sh

if [ `whoami` != root ]; then
    printf "$0 must be run as root.\n"
    exit 1
fi

service gmetad restart
service gmond restart

# gmond doesn't restart unless -n is used here.  Why?
cluster-run -c 'service gmond restart' all

