#!/bin/sh -e

##########################################################################
#   Script description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2016-08-15  root        Begin
##########################################################################

usage()
{
    printf "Usage: $0 [node ...]\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# = 0 ]; then
    nodes=$(cluster-compute-nodes)
else
    nodes="$@"
fi

repo=/usr/local/cluster/sync-files
if [ ! -d $repo ]; then
    printf "$0: No files to sync.\n"
    exit 0
fi

cat << EOM

This will distribute $repo to all specified compute nodes.
EOM

printf "Are you sure you want to proceed? y/[n] "
read resp
if [ 0$resp != 0y ]; then
    exit 0
fi

cd $repo
set +e  # Rsync may return non-zero status
for node in $nodes; do
    rsync -avR * ${node}:/
done

case `auto-ostype` in
FreeBSD)
    # Assume login.conf was modified.  No harm in this.
    printf "Rebuilding login.conf db...\n"
    cluster-run 'cap_mkdb /etc/login.conf' compute
    ;;
*)
    ;;
esac

