#!/bin/sh -e

##########################################################################
#   Script description:
#       Synchronize local password from head node to all relavant nodes
#       
#   History:
#   Date        Name        Modification
#   2015-06-11  J Bacon     Begin
##########################################################################

usage()
{
    printf "Usage: $0 username\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 1 ]; then
    usage
fi

if [ `hostname -s` != login ]; then
    printf "$0 can only be run from the login node.\n"
    exit 1
fi

# This script is called from cluster-passwd, which runs suid root.
# Prevent malicious users from running imposter programs.
PATH=/usr/pkg/sbin:/usr/pkg/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

user_name=$1
os_type=`auto-ostype`

case $os_type in
FreeBSD)
    prefix=/usr/local
    master_pw=/etc/master.passwd
    ;;

RHEL)
    prefix=`auto-pkgsrc-prefix`
    master_pw=/etc/shadow
    ;;

*)
    printf "Unsupported OS: $os_type\n"
    exit 1
    ;;

esac

pw="`awk -F : '$1 == "'$user_name'" { print $2 }' $master_pw`"
if [ "0$pw" = 0 ]; then
    printf "No such user: $user_name\n"
    exit 1
fi

$prefix/sbin/cluster-run -c "auto-transfer-pw $user_name '$pw'" backup io vis compute
