#!/bin/sh -e

##########################################################################
#   Script description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2014-01-01  root        Begin
##########################################################################

usage()
{
    printf "Usage: $0 local-path remote-path io|compute|all perms\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ `hostname -s` != 'login' ]; then
    printf "$0 can only be run on the primary login node.\n"
    exit 1
fi

if [ $# != 4 ]; then
    usage
fi

file=$1
dest_dir=$2
node_type=$3
perms=$4

if [ $node_type = 'io' ] || [ $node_type = 'all' ]; then
    for node in `cluster-io-nodes`; do
	printf "$node...\n"
	scp $file ${node}:$dest_dir
	ssh $node chmod $perms $dest_dir/`basename $file`
    done
fi

if [ $node_type = 'backup' ] || [ $node_type = 'all' ]; then
    for node in `cluster-backup-login-nodes`; do
	printf "$node...\n"
	scp $file ${node}:$dest_dir
	ssh $node chmod $perms $dest_dir/`basename $file`
    done
fi

if [ $node_type = 'compute' ] || [ $node_type = 'all' ]; then
    for node in `cluster-compute-nodes`; do
	printf "$node...\n"
	scp $file ${node}:$dest_dir
	ssh $node chmod $perms $dest_dir/`basename $file`
    done
fi

