#!/bin/sh -e

##########################################################################
#   Function description:
#       Pause until user presses return
##########################################################################

pause()
{
    local junk
    
    printf "Press return to continue..."
    read junk
}

# cluster-zfs-nodes is temporarily added to specific admin scripts for
# testing.  When all cluster-admin components are tested in a heterogeneous
# environment, it should be removed and those nodes included in io-nodes
for node in `cluster-io-nodes` `cluster-zfs-nodes`; do
    echo $node
    ssh $node w
    pause
    ssh -t $node iftop
    ssh -t $node iftop -i ib0 || true   # May not be an IB interface
    printf "Update? y/[n] "
    read update
    if [ 0$update = 0y ]; then
	# CentOS 7 ssh always returns non-zero when rebooting
	ssh -t $node auto-update-system --binary+reboot || true
    fi
done
