#!/bin/sh

##########################################################################
#   Script description:
#       Main menu for cluster admin tasks
#       
#   History:
#   Date        Name        Modification
#   2014-01-08  J Bacon     Begin
##########################################################################

usage()
{
    printf "Usage: $0\n"
    exit 1
}


##########################################################################
#   Function description:
#       Pause until user presses return
##########################################################################

pause()
{
    local junk
    
    printf "Press return to continue..."
    read junk
}


##########################################################################
#   Main
##########################################################################

if [ $# != 0 ]; then
    usage
fi

while true; do

    clear
    spcm-banner
    cat << EOM

1.. Update manager
2.. User manager
3.. Node manager
4.. Software manager
5.. Diagnostics and Monitoring
6.. Restart services
7.. Shut down cluster
Q.. Quit

EOM

    printf "Selection? "
    read selection
    clear
    case $selection in
    1)
	cluster-update-menu
	;;
    
    2)
	cluster-user-admin
	;;
    
    3)
	cluster-node-admin
	;;
    
    4)
	cluster-software-manager
	;;
    
    5)
	cluster-diagnostics
	;;
    
    6)
	cluster-services-menu
	;;
    
    7)
	cluster-shutdown
	pause
	;;
    Q|q)
	exit 0
	;;
    *)
	printf "Invalid selection: '$selection'\n"
	;;
    esac
done
