#!/bin/sh -e

##########################################################################
#   Script description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2014-11-23  root        Begin
##########################################################################

usage()
{
    printf "Usage: $0 hostname backup|compute|io\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 2 ]; then
    usage
fi

node=$1
if ! echo $node | fgrep -q '.'; then
    printf "No domain name in $node.  Continue? y/[n] "
    read continue
    if [ 0$continue != 0y ]; then
	exit 1
    fi
fi
node_type=$2

case $node_type in
backup|compute|io)
    ;;
*)
    usage
esac

# Hack to get around missing feature in PXE installer
# Should be fixed now: Was apparently a dhcp.conf configuration problem on
# login.mortimer
# gateway=$2

case `auto-ostype` in
RHEL)
    scp /etc/hosts ${node}:/etc
    
    # FIXME: Should this be handled by DHCP?
    ssh $node hostname $node
    ssh $node \
	"sed -i -e 's|HOSTNAME=.*|HOSTNAME=$node|' /etc/sysconfig/network"
    
    # ssh $node 'if ! fgrep GATEWAY /etc/sysconfig/network; then echo "GATEWAY='$gateway'" >> /etc/sysconfig/network; fi; service network restart'
    
    printf "Installing basic tools...\n"
    ssh $node yum install -y subversion rsync
    
    printf "Syncing pkgsrc...\n"
    cluster-sync-pkgsrc $node_type $node
    
    printf "Installing yum updates...\n"
    ssh $node yum update -y
    
    printf "Reboot? ([y]/n) "
    read reboot
    if [ 0$reboot != 0n ]; then
	ssh $node shutdown -r now
    fi
    ;;
*)
    printf "Not yet implemented for `auto-ostype`.\n" >> /dev/stderr
    ;;
esac

# Pull ssh keys from node
auto-ssh-reverse-authorize $node

conf_dir='/usr/local/cluster'
ssh $node "mkdir -p $conf_dir && touch $conf_dir/init-done"

