#!/bin/sh

if [ `whoami` != root ]; then
    printf "$0 can only be run as root.\n"
    exit 1
fi

if ! cluster-check-cron-updates; then
    exit 0
fi

service gmetad restart
service gmond restart

# gmond doesn't restart unless -n is used here.  Why?
cluster-run -c -n 'service gmond restart' all

