#!/bin/sh -e

##########################################################################
#   Script description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2015-06-16  root        Begin
##########################################################################

usage()
{
    printf "Usage: $0 hostname compute|io gateway\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 3 ] || [ 0$2 != 0'compute' ] && [ 0$2 != 0'io' ]; then
    usage
fi

node=$1
node_type=$2
gateway=$3

if [ -z EDITOR ]; then
    EDITOR="vi"
fi

conf_dir='/usr/local/cluster'

case `auto-ostype` in
RHEL)
    # Prevent node from being enabled in the scheduler

    if ! ssh $node test -e $conf_dir/init-done; then
	cluster-init-node $node $gateway
    fi
    
    # Sync users
    # FIXME: Don't assume slurm
    if ! ssh $node test -e $conf_dir/user-sync-done; then
	node-sync-user $node slurm || true
	node-sync-all-users $node || true
	ssh $node touch $conf_dir/user-sync-done
    fi
    
    # Sync sys files
    cluster-sync-sysfiles $node
    
    # Temporary
    rsync -av /usr/pkg-1/sbin/cluster-setup ${node}:/usr/pkg-1/sbin
    
    cluster-sync-files
    
    # hosts.allow
    rsync -av /etc/hosts.allow $node:/etc
    
    # Other stuff
    
    # Sync software
    printf "Installing local packages...\n"
    ssh $node yum install -y `cat /usr/local/cluster/$node_type-node-yum-packages`
    
    # Run cluster-setup compute
    # Do this last, since it enables the scheduler
    ssh -t $node cluster-setup $node_type
    
    printf "Be sure to wait until the node reboots before restarting SLURM.\n"
    ;;
*)
    printf "Not yet implemented for `auto-ostype`.\n"
    exit 1
    ;;
esac

# FIXME: Support other schedulers
scontrol update nodename=$node state=resume

