#!/bin/sh

##########################################################################
#   Script description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2014-01-16  root        Begin
##########################################################################

usage()
{
    printf "Usage: $0 \n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 0 ]; then
    usage
fi

if [ `hostname -s` != 'login' ]; then
    printf "$0 can only be run from the head node.\n"
    exit 1
fi

if [ `whoami` != 'root' ]; then
    printf "$0 can only be run by root.\n"
    exit 1
fi

os_type=`auto-ostype`
case $os_type in
FreeBSD)
    flag='-p'
    ;;
RHEL)
    flag='-h'
    ;;
*)
    printf "$os_type is not yet supported.\n"
    exit 1
esac

printf "Shut down compute nodes? (yes/[no]) "
read sure
if [ 0$sure = 0yes ]; then
    for node in `cluster-compute-nodes`; do
	if ping -c 1 -q $node > /dev/null 2>&1; then
	    printf "Shutting down $node...\n"
	    ssh $node shutdown $flag now || true
	else
	    printf "$node is not responding.  Moving on...\n"
	fi
    done
fi

printf "Shut down I/O nodes? (yes/[no]) "
read sure
if [ 0$sure = 0yes ]; then
    cluster-run -c "shutdown $flag now" io
fi

printf "Shut down backup login nodes? (yes/[no]) "
read sure
if [ 0$sure = 0yes ]; then
    cluster-run -c "shutdown $flag now" backup
fi

printf "Shut down visualization nodes? (yes/[no]) "
read sure
if [ 0$sure = 0yes ]; then
    cluster-run -c "shutdown $flag now" vis
fi

printf "Shut down head node? (yes/[no]) "
read sure
if [ 0$sure = 0yes ]; then
    shutdown $flag now
fi

