#!/bin/sh -e

##########################################################################
#   Script description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2015-06-11  root        Begin
##########################################################################

usage()
{
    printf "Usage: $0 username\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 1 ]; then
    usage
fi

# Caution: Be careful not to replace %%PREFIX%% with a hard-coded
# prefix from an installed script.
prefix=%%PREFIX%%

# This script is called from cluster-passwd, which runs suid root.
# Prevent malicious users from running imposter programs.
PATH=$prefix/sbin:$prefix/bin:/bin:/sbin:/usr/bin:/usr/sbin

user_name=$1
os_type=`$prefix/sbin/auto-ostype`
case $os_type in
FreeBSD)
    master_pw=/etc/master.passwd
    ;;
RHEL)
    master_pw=/etc/shadow
    ;;
*)
    printf "Unsupported OS: $os_type\n"
    exit 1
    ;;
esac

$prefix/sbin/cluster-restore-pw $user_name $master_pw

