#!/bin/sh -e

# ${PREFIX} is prepended by install script
if ! fgrep -q lowest-uid cluster-admin.conf; then
    printf "Lowest UID for regular users on this cluster? [1000] " >> `tty`
    read lowest_uid
    if [ 0$lowest_uid = 0 ]; then
	lowest_uid=1000
    fi
    printf "lowest-uid $lowest_uid\n" >> cluster-admin.conf
fi

awk '$1 == "lowest-uid" { print $2 }' cluster-admin.conf

