#!/bin/sh -e

##########################################################################
#   Script description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2017-04-01  root        Begin
##########################################################################

usage()
{
    printf "Usage: $0 expire-days [warning-days, default=14]\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

case $# in
1)
    warning=14
    ;;
2)
    warning=$2
    ;;
*)
    usage
esac
days=$1

for user in `cluster-users`; do
    echo $user
    
    cluster-passwd-user-expiration $user $days $warning
done
