#!/bin/sh -e

##########################################################################
#   Script description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2013-12-28  root        Begin
##########################################################################

usage()
{
    printf "Usage: $0 username uid primary-group-name 'Comment' shell [additional useradd flags]\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ `hostname -s` != 'login' ]; then
    printf "$0 can only be run on the primary login node.\n"
    exit 1
fi

if [ `whoami` != root ]; then                                                   
    printf "$0 must be run as root.\n"                                          
    exit 1                                                                      
fi                                                                              

if [ $# -lt 5 ]; then
    usage
fi

CONF_DIR=/usr/local/cluster

os_type=`auto-ostype`

user_name="$1"
user_id="$2"
group_name="$3"
gecos="$4"
shell="$5"
shift; shift; shift; shift; shift

printf "Checking cluster integrity.  One moment please...\n"
if ! cluster-down-nodes; then
    cat << EOM

Nodes are currently down.  The useradd operation will not be able to complete.
You will need to node-sync-user for the nodes listed above after they are
restored.

EOM
    printf "Continue anyway? y/[n] "
    read continue
    if [ 0$continue != 0y ]; then
	exit
    fi
fi

# Create group if necessary
found_name=`awk -F : '$1 == "'$group_name'" { print $1 }' /etc/group`
if [ 0$found_name = 0$group_name ]; then
    printf "$group_name already exists.\n"
else
    printf "Creating $group_name\n"
    case $os_type in
    FreeBSD)
	pw groupadd $group_name -g $user_id
	;;
    RHEL)
	groupadd -g $user_id $group_name
	;;
    *)
	printf "Unsupported OS: $os_type\n"
	exit 1
	;;
    esac
fi

# Create user
case $os_type in
RHEL)
    useradd -c "$gecos" -g $group_name -m -s $shell -u $user_id $@ \
	$user_name
    # FIXME: Merge ssh-keygen-for-user with cluster-ssh-keygen
    ssh-keygen-for-user $user_name
    ;;
FreeBSD)
    pw useradd $user_name -c "$gecos" -g $group_name -m \
	-s $shell -u $user_id $@
    cluster-ssh-keygen $user_name $group_name
    ;;
*)
    ;;
esac

cluster-sync-user $user_name
if [ 0$NOPW != 0true ]; then
    cluster-passwd $user_name
fi

post_setup=$CONF_DIR/useradd-post-setup
if [ -e $post_setup ]; then
    if auto-file-secure $post_setup; then
	$post_setup $user_name
    else
	exit 1
    fi
else
    printf "No $post_setup found; ignoring.\n"
fi

