#!/bin/sh -e

##########################################################################
#   Script description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2016-05-06  root        Begin
##########################################################################

usage()
{
    printf "Usage: $0 [backup|compute|io node [... node]]\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

case $# in
0)
    compute_nodes=`cluster-compute-nodes`
    backup_nodes="`cluster-backup-login-nodes`"
    other_nodes="`cluster-io-nodes` `cluster-vis-nodes`"
    ;;
1)
    usage
    ;;
*)
    case $1 in
    backup)
	shift
	backup_nodes="$@"
	compute_nodes=""
	other_nodes=""
	;;
    
    io|vis)
	shift
	backup_nodes=""
	compute_nodes=""
	other_nodes="$@"
	;;
    
    compute)
	shift
	backup_nodes=""
	compute_nodes="$@"
	other_nodes=""
	;;
    
    *)
	usage
	;;
    esac
esac

printf "$0 is currently unfinished.\n"
exit 1
