#!/bin/sh -e

##########################################################################
#   Script description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2014-02-24  root        Begin
##########################################################################

usage()
{
    printf "Usage: $0 username groupname\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 2 ]; then
    usage
fi

# 
user_name=$1
group_name=$2

case $os_type in
FreeBSD)
    pw groupmod $group_name -m $user_name
    cluster-run "pw groupmod $group_name -m $user_name" all
    ;;
Linux)
    usermod -a -G $group_name $user_name
    cluster-run "usermod -a -G $group_name $user_name" all
    ;;
*)
    printf "$os_type not yet supported.\n"
    exit 1
    ;;
esac

