#!/bin/sh -e

##########################################################################
#   Script description:
#       Verify that we're running on the head node
#       
#   History:
#   Date        Name        Modification
#   2019-07-16  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0 calling-script-name\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 1 ]; then
    usage
fi

if [ $(cluster-node-type) = head ]; then
    printf "$1 can only be run on the head node.\n"
    exit 1
fi
