#!/bin/sh -e

cluster-dist-file /etc/hosts /etc all 644

for node in \
    `cluster-backup-login-nodes` \
    `cluster-io-nodes` \
    `cluster-compute-nodes`; do
    printf "$node\n"
    cluster-init-node $node
done

