#!/bin/sh -e

##########################################################################
#   Script description:
#       Power on groups of nodes using remote IPMI.
#       Unlike cluster-power-waster, current node state is not considered.
#       FIXME: May want to add exemptions for some drain reasons.
#       
#   History:
#   Date        Name        Modification
#   2020-04-04  Jason Bacon Begin
##########################################################################

usage()
{
    cat << EOM
Usage: $0 [-f first-host] [-l last-host] head|backup|io|compute|vis|all
EOM
    exit 1
}

##########################################################################
#   Main
##########################################################################

if [ $# -lt 1 ]; then
    usage
fi

auto-root-check $0 "Needs to resume compute nodes."

while [ 0`printf '%s' "$1" | cut -c 1,1` = 0'-' ]; do
    if [ $1 = '-f' ]; then
	shift
	first_node=$1
	shift
    elif [ $1 = '-l' ]; then
	shift
	last_node=$1
	shift
    else
	usage $0
    fi
done

if [ $# -lt 1 ]; then
    usage $0
fi

while [ $# -ge 1 ]; do
    node_type=$1
    
    if [ $node_type = 'backup' ] || [ $node_type = 'all' ]; then
	nodes=" `cluster-backup-nodes`"
    fi
    
    if [ $node_type = 'io' ] || [ $node_type = 'all' ]; then
	nodes="$nodes `cluster-file-servers`"
    fi
    
    if [ $node_type = 'vis' ] || [ $node_type = 'all' ]; then
	nodes="$nodes `cluster-vis-nodes`"
    fi
    
    if [ $node_type = 'compute' ] || [ $node_type = 'all' ]; then
	nodes="$nodes `cluster-compute-nodes`"
    fi
    shift
done

# If blank or only spaces
if [ -z "$(echo "$nodes" | sed -e 's| ||g')" ]; then
    printf "No nodes selected.\n"
    exit
fi

if [ -z $first_node ]; then
    first_node=`echo $nodes | awk '{ print $1 }'`
fi
if [ -z $last_node ]; then
    last_node=`echo $nodes | awk '{ print $NF }'`
fi
if ! echo "$nodes" | fgrep -q $first_node; then
    printf "$first_node is not among the selected nodes.\n"
    exit 1
fi
if ! echo "$nodes" | fgrep -q $last_node; then
    printf "$last_node is not among the selected nodes.\n"
    exit 1
fi

in_range=0
for node in $nodes; do
    if [ $node = $first_node ]; then
	in_range=1
    fi
    if [ $in_range = 1 ]; then
	selected_nodes="$selected_nodes $node "
    fi
    if [ $node = $last_node ]; then
	in_range=0
    fi
done

for node in $selected_nodes; do
    printf "\n============================================================\n"
    printf "Starting $node...\n"
    printf "============================================================\n\n"
    
    auto-ipmi-remote-power $node-mgmt on

    if [ $(node-type $node) = compute ]; then
	printf "Resuming $node...\n"
	scontrol update nodename=$node state=resume 2> /dev/null || true
    fi
    
    # Avoid power surge from powering on too many nodes at once
    sleep 5
done
