#!/bin/sh -e

##########################################################################
#   Script description:
#       Add a user to a supplementary group
#
#   Arguments:
#       username
#       groupname
#       
#   History:
#   Date        Name        Modification
#   2014-02-24  J Bacon     Begin
##########################################################################

usage()
{
    printf "Usage: $0 [-c] username groupname\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# -lt 2 ]; then
    usage
fi

if [ `whoami` != 'root' ]; then
    printf "$0 can only be run by root.\n"
    exit 1
fi

if ! cluster-check-cron-updates; then
    exit 0
fi

if [ $1 = -c ]; then
    flags=-c
    shift
fi
user_name=$1
group_name=$2
cluster-run $flags "auto-add-to-group $user_name $group_name" all
