#!/bin/sh -e

##########################################################################
#   Script description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2016-07-27  root        Begin
##########################################################################

usage()
{
    printf "Usage: $0 hostname\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 1 ]; then
    usage
fi

if [ `whoami` != root ]; then
    printf "Only root can run $0.\n"
    exit 1
fi

host=$1

if ! echo $host | fgrep -q '.'; then
    printf "No domain name in $host.\n"
    exit 1
fi

short_host=${host%%.*}
ip=$(awk -v host=$host '$2 == host { print $1 }' /etc/hosts)

set +e

# For root user
ssh-keygen -R $host
ssh-keygen -R $short_host
ssh-keygen -R $ip
for user in $(cluster-users); do
    file=/home/$user/.ssh/known_hosts
    if [ -e $file ]; then
	ssh-keygen -R $host -f $file
	ssh-keygen -R $short_host -f $file
	ssh-keygen -R $ip -f $file
	chown $user $file
    fi
done
