#!/bin/sh

if [ `whoami` != root ]; then
    printf "$0 must be run as root.\n"
    exit 1
fi

if [ $# != 1 ]; then
    printf "Usage: $0 username\n"
    exit 1
fi
user_name=$1

cat << EOM
		
Make sure *ALL* files outside $user_name's home directory are removed or
assigned to another user before you continue.

Files in the home directory will be removed automatically if you choose.

Type "All files removed" when you are done.  Type anything else to abort
the removal.

EOM

read -p 'All files removed? ' removed
if [ 0$removed != 0"All files removed" ]; then
    exit 0
fi

printf "This action cannot be undone!\n"
printf "Are you absolutely sure you want to remove $user_name? yes/[no] "

read resp
if [ 0$resp != 0'yes' ]; then
    exit 0
fi

printf "Save home directory? [yes]/no "
read save_home
if [ x$save_home != xno ]; then
    # Save home dir from removal by rmuser -y
    mkdir -p /home/Archived-users
    mv /home/$user_name /home/Archived-users
fi

# Save user info
mkdir -p /usr/local/cluster
fgrep $user_name /etc/passwd >> /usr/local/cluster/removed-users
fgrep $user_name /etc/group >> /usr/local/cluster/removed-users

# Group should be removed by rmuser, but it isn't!
cluster-run -c "auto-remove-user $user_name" all
auto-remove-user $user_name

