#!/bin/sh -e

##########################################################################
#   Script description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2016-06-07  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0 username\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 1 ]; then
    usage
fi

user_name=$1
os_type=`auto-ostype`

case $os_type in
FreeBSD)
    groups="`groups $user_name | cut -s -d ' ' -f 2- | tr ' ' ','`"
    if [ ! -z $groups ]; then
	for node in `cluster-all-nodes`; do
	    echo $node
	    ssh $node pw usermod $user_name -G "$groups"
	done
    else
	printf "No groups for $user_name.\n"
    fi
    ;;

RHEL)
    groups="`groups $user_name | awk -F ': ' '{print $2}' | cut -s -d ' ' -f 2- | tr ' ' ','`"
    if [ ! -z $groups ]; then
	for node in `cluster-all-nodes`; do
	    echo $node
	    ssh $node usermod -G "$groups" $user_name
	done
    else
	printf "No groups for $user_name.\n"
    fi
    ;;

*)
    printf "$ostype is not yet supported.\n"
    exit 1
    ;;
esac

