#!/bin/sh -e


##########################################################################
#   Function description:
#       Pause until user presses return
##########################################################################

pause()
{
    local junk
    
    printf "Press return to continue..."
    read junk
}

for node in `cluster-vis-nodes`; do
    echo $node
    ssh $node w
    pause
    ssh -t $node iftop
    ssh -t $node iftop -i ib0 || true
    printf "Update? y/[n] "
    read update
    if [ 0$update = 0y ]; then
	ssh $node "wall 'The visualization node will be rebooted shortly in order to complete installation of important security updates.  It should be available again within a few minutes.'"
	ssh -t $node auto-update-system
    fi
done

