#!/bin/sh -e

# This node list is for incremental testing if heterogeneous clusters,
# particularly FreeBSD ZFS file servers in CentOS clusters.
# These nodes will be included in the io-nodes group once all cluster-admin
# components are tested in a heterogeneous environment

# Return 0 status regardless
# The new standard is compute-[0-9]+, .*raid-[0-9]+, and login-[0-9]+
# for all nodes.
# ^data and raid.* are here to allow legacy names on older clusters
awk '$2 ~ "^zfs-.*[0-9]+\\." { print $3 }' /etc/hosts \
    | egrep -ve '-ib0|-mgmt|-hpc|-aux' || true

