#!/bin/sh -e

case $(auto-ostype) in
FreeBSD)
    : ${PORTSDIR:=/usr/ports}
    LOCALBASE=$(cluster-localbase)
    
    if [ -e $PORTSDIR/.svn ]; then
	svn update $PORTSDIR
    else
	portsnap fetch && portsnap update
    fi
    
    if [ -e $LOCALBASE/sbin/wip-update ]; then
	wip-update
    fi
    
    procs=0
    for node in `cluster-all-nodes`; do
	printf "Syncing ports to $node...\n"
	if ! rsync --archive --inplace --delete \
		/usr/ports ${node}:/usr; then
	    printf "$node\n" >> cluster-ports-update-failed-nodes
	fi
    done
    ;;

*)
    printf "$0: Not supported on $(auto-ostype).\n"
    exit 1
    ;;

esac
