#!/bin/sh -e

##########################################################################
#   Script description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2015-05-29  root        Begin
##########################################################################

usage()
{
    printf "Usage: $0 username shadow-file\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 2 ]; then
    usage
fi

# Prevent malicious users from running imposter cluster-restore-pw
# or other scripts.
PATH=%%PREFIX%%/sbin:/bin:/sbin:/usr/bin:/usr/sbin

user_name="$1"
old_shadow_pw="$2"

pw="`awk -F : '$1 == "'$user_name'" { print $0 }' $old_shadow_pw`"
if [ "0$pw" = 0 ]; then
    printf "No such user: $user_name\n"
    exit 1
fi
%%PREFIX%%/sbin/auto-restore-pw $user_name "$pw"
if [ $user_name = root ]; then
    %%PREFIX%%/sbin/cluster-run "auto-restore-pw $user_name '$pw'" all
else
    %%PREFIX%%/sbin/cluster-run "auto-restore-pw $user_name '$pw'" backup io vis
fi

