#!/bin/sh -e

##########################################################################
#   Script description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2017-03-31  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0 username new_group|new-gid [directory ...]\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# -lt 2 ]; then
    usage
fi

auto-root-check $0

if ! cluster-check-cron-updates; then
    exit 0
fi

# Caution: 
# The line below is modified by install. Be careful not to replace
# %%PREFIX%% with a hard-coded prefix from an installed script.
prefix=%%PREFIX%%

user_name=$1
new_group=$2
shift
shift

# Verify that all dirs exits before changing anything!
dirs="$@"
for dir in $dirs; do
    if [ ! -e $dir ]; then
	printf "$0: ${dir}: No such file or directory.\n"
	exit 1
    fi
done

auto-change-primary-group $user_name $new_group $dirs
cluster-run "auto-change-primary-group $user_name $new_group" backup io vis compute
# FIXME: Should $prefix/etc/spcm be hard-coded?
chgrp $new_group $prefix/etc/spcm/pw-age/$user_name
