#!/bin/sh -e

# FIXME: Separate node type from hostname
if [ $(hostname -s) = login ]; then
    printf "head\n"
elif hostname -s | fgrep -q compute-; then
    printf "compute\n"
elif hostname -s | fgrep -q raid-; then
    printf "io\n"
elif hostname -s | fgrep -q vis-; then
    printf "vis\n"
else
    printf "unknown\n"
fi
