#!/bin/sh

##########################################################################
#   Script description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2014-01-16  root        Begin
##########################################################################

usage()
{
    printf "Usage: $0 \n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 0 ]; then
    usage
fi

if [ `hostname -s` != 'login' ]; then
    printf "$0 can only be run from the head node.\n"
    exit 1
fi

if [ `whoami` != 'root' ]; then
    printf "$0 can only be run by root.\n"
    exit 1
fi

os_type=`uname`
case $os_type in
FreeBSD)
    flag='-p'
    ;;
Linux)
    flag='-h'
    ;;
*)
    printf "$os_type is not yet supported.\n"
    exit 1
esac

printf "Shut down compute nodes? (yes/[no]) "
read sure
if [ 0$sure = 0yes ]; then
    cluster-run -c 'shutdown $flag now' compute
fi

printf "Shut down I/O nodes? (yes/[no]) "
read sure
if [ 0$sure = 0yes ]; then
    cluster-run -c 'shutdown $flag now' io
fi

printf "Shut down backup login nodes? (yes/[no]) "
read sure
if [ 0$sure = 0yes ]; then
    cluster-run -c 'shutdown $flag now' backup
fi

printf "Shut down visualization nodes? (yes/[no]) "
read sure
if [ 0$sure = 0yes ]; then
    cluster-run -c 'shutdown $flag now' vis
fi

printf "Shut down head node? (yes/[no]) "
read sure
if [ 0$sure = 0yes ]; then
    shutdown $flag now
fi

