#!/bin/sh -e

##########################################################################
#   Script description:
#       Wait until all updated nodes are resumed.
#
#   History:
#   Date        Name        Modification
#   2021-09-20  Charlie &   Begin
##########################################################################

usage()
{
    printf "Usage: $0\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 0 ]; then
    usage
fi

log_dir="/usr/local/var/log/lpjs"
while ! lpjs-resume-updated-nodes; do
    printf "Some nodes still down.  Retrying in 10 seconds...\n"
    sleep 10
done
