#!/bin/sh -e

##########################################################################
#   Script description:
#       Resume scheduling on one or more compute nodes.
#
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2015-06-18  root        Begin
##########################################################################

usage()
{
    printf "Usage: $0 node-spec\n"
    exit 1
}


##########################################################################
#   Function description:
#       Pause until user presses return
##########################################################################

pause()
{
    local junk
    
    printf "Press return to continue..."
    read junk
}

##########################################################################
#   Main
##########################################################################

if [ $# != 1 ]; then
    usage
fi

cat << EOM

Make sure all nodes are up-to-date before resuming them.

o   Install all security updates

o   Run cluster-sync-node if necessary.

EOM
printf "Proceed with resume? y/[n] "
read proceed

if [ 0$proceed = 0y ]; then
    scontrol update state=resume nodename="$1"
fi

