#!/bin/sh -e

LOCALBASE=$(cluster-localbase)

files=$LOCALBASE/etc/slurm.conf
if [ -e $LOCALBASE/etc/cgroup.conf ]; then
    files="$files $LOCALBASE/etc/cgroup.conf"
fi
for node in $(cluster-compute-nodes); do
    printf "\n$node...\n"
    scp -p $files ${node}:$LOCALBASE/etc
done
slurm-sync-backup

