#!/bin/sh -e

export PATH=${PATH}:/usr/local/bin:/usr/local/sbin
nodelist=$(scontrol show hostnames $@)
for node in $nodelist; do
    ssh $node shutdown -p now
done
log=/home/slurm/node-suspend.log
printf "Suspending $1 at $(date)\n" >> $log
tail -100 $log > $log.tmp
mv -f $log.tmp $log
