#!/bin/sh -e

##########################################################################
#   Script description:
#       Drain all compute nodes
#
#   Arguments:
#       Reason for use with scontrol update
#
#   History:
#   Date        Name        Modification
#   2017-07-05  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0 'reason'\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 1 ]; then
    usage
fi

reason="$1"
for node in `cluster-compute-nodes`; do
    echo $node
    scontrol update state=drain reason="$reason" nodename=$node
done
