#!/bin/sh -e

down_nodes=`sinfo -h -o '%E %T %n' | awk '$1 == "slurm-update-idle-nodes" && $2 ~ "down" { print $3 }'`

# For debugging
#down_nodes=`sinfo -h -o '%E %T %n' | awk '$1 == "none" && $2 ~ "idle" { print $3 }'`

for node in $down_nodes; do
    printf "Resuming $node...\n"
    # Scontrol reports invalid node state with resume sometimes.  This
    # seems to fix it.
    scontrol update state=down nodename=$node
    scontrol update state=resume nodename=$node
done

