#!/bin/sh -e

# Caution: 
# The line below is modified by install.sh. Be careful not to replace
# %%PREFIX%% with a hard-coded prefix from an installed script.
prefix=%%PREFIX%%

# Backup controller needs to save state info to the same location as
# primary controller
sed -e 's|StateSaveLocation=/home/slurm/slurmctld|StateSaveLocation=/head_home/slurm/slurmctld|' \
    $prefix/etc/slurm.conf > $prefix/etc/slurm.conf.backup-node
for node in `cluster-backup-login-nodes`; do
    printf "Syncing slurm.conf to $node...\n"
    rsync -pog $prefix/etc/slurm.conf.backup-node ${node}:$prefix/etc/slurm.conf
done

