#!/bin/sh -e

##########################################################################
#   Function description:
#       Pause until user presses return
##########################################################################

pause()
{
    local junk
    
    printf "Press return to continue..."
    read junk
}

resp=''
while [ 0$resp != 0q ]; do
    clear
    cat << EOM
    
			     **********************
				SLURM Admin Menu
			     **********************

1.. Restart scheduler daemons
2.. Mark a node as down
3.. Mark a node as available
4.. Show cores per user
5.. Show cluster load
6.. Resume all updated nodes currently marked down
Q.. Quit

EOM

    printf 'Selection? '
    read resp
    case $resp in
    1)
	slurm-restart
	pause
	;;
    2)
	sinfo
	printf "Node number? (e.g. 1-01) "
	read node
	scontrol update State=down NodeName=compute-$node
	sinfo
	printf "Update slurm.conf if this is a long-term outage.\n"
	pause
	;;
    3)
	sinfo
	printf "Node number? (e.g. 1-01) "
	read node
	scontrol update State=resume NodeName=compute-$node
	sinfo
	printf "Update slurm.conf if necessary.\n"
	pause
	;;
    4)
	slurm-user-cores
	pause
	;;
    5)
	slurm-cluster-load
	pause
	;;
    6)
	slurm-resume-updated-nodes
	sinfo
	pause
	;;
    Q|q)
	;;
    *)
	printf "Invalid selection: $resp\n"
	pause
    esac
done

