#!/bin/sh -e

LOCALBASE=$(cluster-localbase)

# Backup controller needs to save state info to the same location as
# primary controller
sed -e 's|StateSaveLocation=/home/slurm/slurmctld|StateSaveLocation=/head_home/slurm/slurmctld|' \
    $LOCALBASE/etc/slurm.conf > $LOCALBASE/etc/slurm.conf.backup-node
for node in `cluster-backup-nodes`; do
    printf "Syncing slurm.conf to $node...\n"
    rsync -pog $LOCALBASE/etc/slurm.conf.backup-node ${node}:$LOCALBASE/etc/slurm.conf
    if [ -e $LOCALBASE/etc/cgroup.conf ]; then
	rsync -pog $LOCALBASE/etc/cgroup.conf ${node}:$LOCALBASE/etc
    fi
done
rm -f $LOCALBASE/etc/slurm.conf.backup-node
