#!/bin/sh -e

# sinfo -o '%E %T %n'

# FIXME: This does not limit resume to updated nodes, but resumes
# any node that was unexpectedly rebooted.
# Reason set when draining is overwritten at reboot
down_nodes=`sinfo -h -o '%E %T %n' | \
    awk '$2 == "unexpectedly" && $4 ~ "down" { print $5 }'`

# For debugging
#down_nodes=`sinfo -h -o '%E %T %n' | awk '$1 == "none" && $2 ~ "idle" { print $3 }'`

for node in $down_nodes; do
    printf "Resuming $node...\n"
    # Scontrol reports invalid node state with resume sometimes.  This
    # seems to fix it.
    scontrol update state=down nodename=$node
    scontrol update state=resume nodename=$node
done

