#!/bin/sh -e

case $(auto-ostype) in
FreeBSD)
    # FreeBSD ports
    wip-update
    # Use -f to avoid removing auto-admin dependents
    pkg remove -fy auto-admin || true
    wip-reinstall-port -nu -r spcm
    ;;

Darwin|NetBSD|RHEL)
    # pkgsrc
    pkgsrc=$(auto-pkgsrc-dir)
    cd $pkgsrc/wip
    git pull
    
    # Allow auto-admin deinstall
    pkg_delete -fy auto-admin spcm || true
    wip-reinstall-port -nu -r spcm
    ;;

*)
    printf "$0: Not supported on $(auto-ostype)\n"
    exit 1
esac
