#!/bin/sh -e

case $(auto-ostype) in
FreeBSD)
    # FreeBSD ports
    wip-update
    pkg remove -y auto-admin
    wip-reinstall-port -nu -r spcm
    ;;

Darwin|NetBSD|RHEL)
    # pkgsrc
    pkgsrc=$(auto-pkgsrc-dir)
    cd $pkgsrc/wip
    git pull
    
    # Allow auto-admin deinstall
    pkgin remove -y auto-admin spcm || true
    
    cd $pkgsrc/wip/auto-admin
    bmake clean reinstall
    
    cd $pkgsrc/wip/spcm
    bmake clean reinstall
    ;;

*)
    printf "$0: Not supported on $(auto-ostype)\n"
    exit 1
esac
