#!/bin/sh -e

##########################################################################
#   Script description:
#       Report the node type based on hostname
#       
#   History:
#   Date        Name        Modification
#   2020-12-31  Charlie &   Begin
##########################################################################

usage()
{
    printf "Usage: $0 [hostname]\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

LOCALBASE=$(spcm-localbase)

case $# in
0)
    if [ -e $LOCALBASE/etc/spcm/my-node-type ]; then
	cat $LOCALBASE/etc/spcm/my-node-type
    fi
    ;;

1)
    hostname=$1
    # $1 is FQDN
    if awk '{ print $1 }' $LOCALBASE/etc/spcm/node-types | fgrep -qx $hostname; then
	fqdn=$hostname
    else
	# $1 is short hostname
	fqdn=$(awk -v host=$hostname '$3 == host { print $2 }' /etc/hosts)
	if [ -z $fqdn ]; then
	    # $1 is just a number, as in 001 from compute-001
	    hostname=compute-$hostname
	    fqdn=$(awk -v host=$hostname '$3 == host { print $2 }' /etc/hosts)
	fi
    fi
    if [ -e $LOCALBASE/etc/spcm/node-types ]; then
	# short_host=$(echo $1 | cut -d . -f 1)
	awk -v hostname=$fqdn '$1 == hostname { print $2 }' \
	    $LOCALBASE/etc/spcm/node-types
    fi
    ;;

*)
    usage
    ;;

esac
