#!/bin/sh -e

##########################################################################
#   Script description:
#       Echo LOCALBASE for the current OS
#       
#   History:
#   Date        Name        Modification
#   2021-01-05  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 0 ]; then
    usage
fi

case $(auto-ostype) in
Darwin)
    echo /opt/pkg
    ;;

FreeBSD)
    echo /usr/local
    ;;

NetBSD|RHEL)
    echo /usr/pkg
    ;;

*)
    printf "$0: Not supported on $(auto-ostype).\n"
    exit 1
    ;;

esac
