#!/bin/sh -e

case 0$(which cluster-setup) in
0/usr/local/sbin/cluster-setup)
    # FreeBSD ports
    wip-update
    pkg remove -y auto-admin
    wip-reinstall-port -nu -r spcm
    ;;

0/usr/pkg/sbin/cluster-setup)
    # pkgsrc
    pkgsrc=$(auto-pkgsrc-dir)
    cd $pkgsrc/wip
    git pull
    
    # Allow auto-admin deinstall
    pkgin remove -y auto-admin spcm || true
    
    cd $pkgsrc/uwm-pkgsrc-wip/auto-admin
    bmake distclean && bmake deinstall && bmake install
    
    cd $pkgsrc/uwm-pkgsrc-wip/spcm
    bmake distclean && bmake deinstall && bmake install
    
    cd ..
    yes | ./clean-all
    ;;

*)
    printf "No spcm installation found.\n"
    exit 1
esac
