#!/bin/sh -e

##########################################################################
#   Script description:
#       Change NFSD count on all io servers
#
#   History:
#   Date        Name        Modification
#   2019-02-08  J Bacon     Begin
##########################################################################

usage()
{
    printf "Usage: $0 min-server-count max-server-count\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 2 ]; then
    usage
fi

min_count=$1
max_count=$2

spcm-run "auto-change-nfsd-count $min_count $max_count" io
