#!/bin/sh

##########################################################################
#   Script description:
#       Conveniently run ps on a cluster node
#       
#   History:
#   Date        Name        Modification
#   2013-05-01  Jason Bacon Begin
##########################################################################

usage()
{
    cat << EOM

Usage: $0 complete-spcm-node-name|compute-spcm-node-index [iftop flags]

If the compute-<argument> is a valid compute node host name, then compute-
is automatically prepended.

Example:
    spcm-node-iftop 002         # same as spcm-node-iftop compute-002
    spcm-node-iftop compute-002
    spcm-node-iftop 256g-004
    spcm-node-iftop compute-256g-001
    spcm-node-iftop raid-01 -i ib0

EOM
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# -lt 1 ]; then
    usage
fi

node=$1
shift
if [ 0$(spcm-node-type compute-$node) = 0compute ]; then
    node=compute-$node
fi

if ! (awk '{ print $2 }' /etc/hosts | fgrep -x $node || \
    awk '{ print $3 }' /etc/hosts | fgrep -x $node); then
    printf "$0: $node not found in /etc/hosts.\n"
    exit 1
fi

ssh -t $node iftop "$@"
