#!/bin/sh -e

##########################################################################
#   Script description:
#       Display ASCII art banner
#       https://www.ascii-art-generator.org/
#       Font type: Slant
#
#   History:
#   Date        Name        Modification
#   2020-04?    Jason Bacon Begin
##########################################################################

cat << EOM
	  _____ ____  ________  ___   __________________________________
	 / ___// __ \/ ____/  |/  /
	 \__ \/ /_/ / /   / /|_/ /     Simple, Portable Cluster Manager
	___/ / ____/ /___/ /  / /      http://acadix.biz/spcm.php
       /____/_/    \____/_/  /_/      __________________________________
EOM
