#!/bin/sh -e

auto-root-check $0 "Needs to resume compute nodes."

drained_nodes=$(sinfo -h -o '%T %E %n' | awk '$1 ~ "drained" && $2 == "power-save" { print $3 }')

for node in $drained_nodes; do
    read -p "Resume $node? [y]/n " resume
    if [ 0$resume != 0n ]; then
	auto-ipmi-remote-power $spcm-node-mgmt on
	scontrol update nodename=$node state=resume
	
	# Avoid power surge from powering on too many nodes at once
	sleep 4
    fi
done
