#!/bin/sh -e

##########################################################################
#   Script description:
#       Disable local password for user, so they must use a service
#       such as LDAP or AD, or are locked out of the system.
#   
#   History:
#   Date        Name        Modification
#   2019-06-25  Jason Wayne Bacon - UITS/UITS - SysadminBegin
##########################################################################

usage()
{
    printf "Usage: $0 username\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 1 ]; then
    usage
fi

auto-root-check $0
spcm-head-check $0

if ! spcm-check-cron-updates; then
    exit 0
fi

user_name=$1

spcm-run "auto-unlock-local-pw $user_name" all
