#!/bin/sh

service slurmctld stop
for node in compute-007 compute-008; do
    ssh $node service slurmd stop
done

service slurmctld start
for node in compute-007 compute-008; do
    ssh $node service slurmd start
done

