#!/bin/sh -e

##########################################################################
#   Script description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2013-12-28  root        Begin
##########################################################################

usage()
{
    printf "Usage: $0 username uid gid 'Comment' home shell\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ `hostname -s` != 'login' ]; then
    printf "$0 can only be run on the primary login node.\n"
    exit 1
fi

case $# in
6)
    user_name="$1"
    user_id="$2"
    group_id="$3"
    gecos="$4"
    home="$5"
    shell="$6"
    ;;
*)
    usage
esac

# Create group if necessary

# Create user
useradd -c "$gecos" -d $home -g $group_id -m -s $shell -u $user_id $user_name

cluster-finish-user $user_name

