#!/bin/sh -e

# Caution: 
# The line below is modified by install. Be careful not to replace
# %%PREFIX%% with a hard-coded prefix from an installed script.
prefix=%%PREFIX%%

db=$prefix/etc/spcm/compute-node-yum-packages

if [ ! -e $db ]; then
    cat << EOM

Missing $db.

$db should contain a list of packages to be installed on every compute node,
all on a single line.

EOM
cat $db

