#!/bin/sh -e

##########################################################################
#   Script description:
#       Generate a random passphrase consisting of 3 words and
#       2 separators.
#       Using /usr/share/dict/words on FreeBSD 9.2, which has 235,924
#       words, there are
#
#           235924^3*25^2 = 8,207,225,875,605,640,000
#
#       possible passphrases.
#
#       A classic 8-character completely random password using printable
#       characters by contrast has only
#
#           95^8          =     6,634,204,312,890,625
#   
#       possible patterns (which are much harder to remember).
#
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2014-01-05  root        Begin
##########################################################################

# CentOS: yum install words

##########################################################################
#   Function description:
#       Pause until user presses return
##########################################################################

pause()
{
    local junk
    
    printf "Press return to continue..."
    read junk
}

cat << EOM
===========================================================================
If no one can see your computer screen right now, you may use one of the
suggested passphrases about to be displayed.  Otherwise, make up one of
your own consisting of three words separated by random characters and
modified with a random capital letters or other characters inserted.
===========================================================================
EOM
pause
printf '\n'

c=1
while [ $c -lt 10 ]; do
    # Pull 3 random words from the dictionary
    dict='/usr/share/dict/words'
    dict_size=`wc -l $dict | cut -d ' ' -f 1`
    rand=$(($RANDOM * $RANDOM % $dict_size))
    word1=`awk -v line=$rand 'FNR == line { print }' $dict`
    rand=$(($RANDOM * $RANDOM % $dict_size))
    word2=`awk -v line=$rand 'FNR == line { print }' $dict`
    rand=$(($RANDOM * $RANDOM % $dict_size))
    word3=`awk -v line=$rand 'FNR == line { print }' $dict`
    
    # Pick 2 random non-letter charactes as separators
    chars='1 2 3 4 5 6 7 8 9 0 ! @ # $ % ^ & - _ = + , . : ;'
    rand=$(($RANDOM % 24 + 1))
    sep1=`echo $chars | cut -d ' ' -f $rand`
    rand=$(($RANDOM % 24 + 1))
    sep2=`echo $chars | cut -d ' ' -f $rand`
    
    # Paste them together
    printf "%s%c%s%c%s\n" $word1 $sep1 $word2 $sep2 $word3
    c=$((c + 1))
done

