#!/bin/sh -e

squeue --states=pending -o '%6A %8u %2t %4C %3D %3h %8j %E'

printf '\n'
sinfo -o '%C'

allocated=`sinfo -h -o '%C' | awk -F '/' ' { print $1 }'`
total=`sinfo -h -o '%C' | awk -F '/' ' { print $4 }'`
load=$((allocated * 100 / total))
printf "\nLoad: %s%%\n" $load

