#!/bin/sh -e

cat << EOM

This action will upgrade all installed packages and all ports frameworks
on all nodes.  A reboot of all nodes may be required.

EOM

printf "Are you sure you want to proceed? (yes/[no]) "
read resp
if [ 0$resp != 0yes ]; then
    exit 0
fi

cache_dir=`cluster-pkgdir`
env PKG_CACHEDIR=$cache_dir pkg upgrade -y
cluster-run "env PKG_CACHEDIR=$cache_dir pkg upgrade -y"
cluster-ports-update

