#!/bin/sh -e

##########################################################################
#   Script description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2015-04-14  Charlie &   Begin
##########################################################################

usage()
{
    printf "Usage: $0 old-node new-node\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 2 ]; then
    usage
fi

old_node=$1
new_node=$2

packages=`ssh $old_node pkg info | awk ' { print $1 }'`
rm -f $new_node.installed $new_node.failed
set +e
for pkg in $packages; do
    basename=`echo ${pkg%%-[0-9]*}`
    echo $basename
    if ssh $new_node pkg install -y $basename; then
	echo $pkg >> $new_node.installed
    else
	echo $pkg >> $new_node.failed
    fi
done

