#!/bin/sh -e

: ${PORTSDIR:=/usr/ports}

if [ -e $PORTSDIR/.svn ]; then
    svn update $PORTSDIR
else
    portsnap fetch && portsnap update
fi

if [ -e /usr/local/sbin/wip-update ]; then
    wip-update
fi

procs=0
for node in `cluster-all-nodes`; do
    printf "Syncing ports to $node...\n"
    if ! rsync -a --size-only --inplace --delete /usr/ports ${node}:/usr; then
	printf "$node\n" >> cluster-ports-update-failed-nodes
    fi
done

