#!/bin/sh -e

##########################################################################
#   Script description:
#       Sync core system packages from one node to another
#
#   Arguments:
#       1)  Source node
#       2)  Target node
#       
#   History:
#   Date        Name        Modification
#   2015-04-14  J Bacon     Begin
#
#   FIXME: Merge this with CentOS cluster-sync-yum-packages
#
##########################################################################

usage()
{
    printf "Usage: $0 old-node new-node\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 2 ]; then
    usage
fi

old_node=$1
new_node=$2

packages=`ssh $old_node pkg info | awk ' { print $1 }'`
rm -f $new_node.installed $new_node.failed
set +e
for pkg in $packages; do
    basename=`echo ${pkg%%-[0-9]*}`
    base_packages="$base_packages $basename"
done
echo $base_packages
ssh $new_node pkg install -y "$base_packages"
