#!/bin/sh -e

if [ $# != 1 ]; then
    printf "Usage: $0 package-name\n"
    exit 1
fi

if [ `whoami` != root ]; then
    printf "$0 must be run as root.\n"
    exit 1
fi

cache_dir=`cluster-pkgdir`
# Caution: 
# The line below is modified by install. Be careful not to replace
# %%PREFIX%% with a hard-coded prefix from an installed script.
prefix=%%PREFIX%%

pkg=$1
cluster-run "env PKG_CACHEDIR=$cache_dir cluster-local-pkg-install $pkg" compute

auto-append-line $pkg $pkg $prefix/etc/spcm/packages.txt nocomment

